// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apisdosv1beta1 "github.com/nginx/kubernetes-ingress/pkg/apis/dos/v1beta1"
	versioned "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nginx/kubernetes-ingress/pkg/client/informers/externalversions/internalinterfaces"
	dosv1beta1 "github.com/nginx/kubernetes-ingress/pkg/client/listers/dos/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DosProtectedResourceInformer provides access to a shared informer and lister for
// DosProtectedResources.
type DosProtectedResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() dosv1beta1.DosProtectedResourceLister
}

type dosProtectedResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDosProtectedResourceInformer constructs a new informer for DosProtectedResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDosProtectedResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDosProtectedResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDosProtectedResourceInformer constructs a new informer for DosProtectedResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDosProtectedResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppprotectdosV1beta1().DosProtectedResources(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppprotectdosV1beta1().DosProtectedResources(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppprotectdosV1beta1().DosProtectedResources(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppprotectdosV1beta1().DosProtectedResources(namespace).Watch(ctx, options)
			},
		}, client),
		&apisdosv1beta1.DosProtectedResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *dosProtectedResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDosProtectedResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dosProtectedResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdosv1beta1.DosProtectedResource{}, f.defaultInformer)
}

func (f *dosProtectedResourceInformer) Lister() dosv1beta1.DosProtectedResourceLister {
	return dosv1beta1.NewDosProtectedResourceLister(f.Informer().GetIndexer())
}
