name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - "enhancement"
  - title: '💣 Breaking Change'
    labels:
      - "change"
  - title: '🐛 Bug Fixes'
    labels:
      - "bug"
  - title: '📝 Documentation'
    labels:
      - "documentation"
  - title: '🔨 Maintenance'
    labels:
      - "chore"
      - "dependencies"
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/enh\/.+/'
      - '/enhancement\/.+/'
      - '/feat\/.+/'
      - '/feature\/.+/'
  - label: 'dependencies'
    files:
      - 'go.mod'
      - 'go.sum'
      - 'vendor*'
    branch:
      - '/deps\/.+/'
filter-by-commitish: true
template: |
  *Help make the NGINX Ingress Controller better by participating in our [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=L_093Ttq0UCb4L-DJ9gcUM6Dh1A0cORCorfgZAMdkwJUREhJUFAyM1ZHRzZLSzQyMUlCNFhXVkZENy4u)!*

  ## New in NGINX Ingress Controller v$NEXT_MINOR_VERSION

  $CHANGES

  ## Upgrade

  - For NGINX, use the v$NEXT_MINOR_VERSION image from our DockerHub: `nginx/nginx-ingress:$NEXT_MINOR_VERSION`, `nginx/nginx-ingress:$NEXT_MINOR_VERSION-alpine` or `nginx/nginx-ingress:$NEXT_MINOR_VERSION-ubi`
  - For NGINX Plus, please build your own image using the v$NEXT_MINOR_VERSION source code.
  - For Helm, use version HELM_VERSION_REPLACE_ME! of the chart.

  ## Resources

  - Documentation -- https://docs.nginx.com/nginx-ingress-controller/
  - Configuration examples -- https://github.com/nginxinc/kubernetes-ingress/tree/v$NEXT_MINOR_VERSION/examples and https://github.com/nginxinc/kubernetes-ingress/tree/v$NEXT_MINOR_VERSION/examples-of-custom-resources
  - Helm Chart -- https://github.com/nginxinc/kubernetes-ingress/tree/v$NEXT_MINOR_VERSION/deployments/helm-chart
  - Operator -- https://github.com/nginxinc/nginx-ingress-operator/
