name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - "enhancement"
  - title: '💣 Breaking Change'
    labels:
      - "change"
  - title: '🐛 Bug Fixes'
    labels:
      - "bug"
  - title: '📝 Documentation'
    labels:
      - "documentation"
  - title: '🧪 Tests'
    labels:
      - "tests"
  - title: '🔨 Maintenance'
    labels:
      - "chore"
  - title: '⬆️ Dependencies'
    labels:
      - "dependencies"
version-resolver:
  major:
    labels:
      - 'change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
      - 'tests'
  default: patch
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'tests'
    branch:
      - '/tests\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/enh\/.+/'
      - '/enhancement\/.+/'
      - '/feat\/.+/'
      - '/feature\/.+/'
    title:
      - '/feat/i'
  - label: 'dependencies'
    files:
      - 'go.mod'
      - 'go.sum'
      - 'vendor*'
    branch:
      - '/deps\/.+/'
filter-by-commitish: true
commitish: master
template: |
  *Help make the NGINX Ingress Controller better by participating in our [survey](https://forms.office.com/Pages/ResponsePage.aspx?id=L_093Ttq0UCb4L-DJ9gcUKLQ7uTJaE1PitM_37KR881UMEs0Rk5PMkYzMTJTWVA0V1hUVTRLUUMyNS4u)!*

  ## New in NGINX Ingress Controller v$RESOLVED_VERSION

  $CHANGES

  ## Upgrade

  - For NGINX, use the v$RESOLVED_VERSION image from our [DockerHub](https://hub.docker.com/r/nginx/nginx-ingress/tags?page=1&ordering=last_updated&name=$RESOLVED_VERSION) or [GitHub Container](https://github.com/nginxinc/kubernetes-ingress/pkgs/container/kubernetes-ingress).
  - For NGINX Plus, use the v$RESOLVED_VERSION image from the F5 Container registry or build your own image using the v$RESOLVED_VERSION source code.
  - For Helm, use version HELM_VERSION_REPLACE_ME! of the chart.

  ## Resources

  - Documentation -- https://docs.nginx.com/nginx-ingress-controller/
  - Configuration examples -- https://github.com/nginxinc/kubernetes-ingress/tree/v$RESOLVED_VERSION/examples and https://github.com/nginxinc/kubernetes-ingress/tree/v$RESOLVED_VERSION/examples-of-custom-resources
  - Helm Chart -- https://github.com/nginxinc/kubernetes-ingress/tree/v$RESOLVED_VERSION/deployments/helm-chart
  - Operator -- https://github.com/nginxinc/nginx-ingress-operator/
