env:
  - CGO_ENABLED=0

builds:
  - id: kubernetes-ingress
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 7
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/nginx-ingress/
    binary: nginx-ingress
  - id: aws
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.productCode={{.Env.AWS_PRODUCT_CODE}} -X main.pubKeyString={{.Env.AWS_PUB_KEY}}
    main: ./cmd/nginx-ingress/
    binary: nginx-ingress
    tags:
      - aws

archives:
  - id: kubernetes-ingress
    builds: [kubernetes-ingress]

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
    ids: [kubernetes-ingress]

release:
  ids: [kubernetes-ingress]

blobs:
  - provider: azblob
    bucket: '{{.Env.AZURE_BUCKET_NAME}}'
    extra_files:
      - glob: ./dist/**.sbom

milestones:
  - close: true

announce:
  slack:
    enabled: true
    channel: '#announcements'
    message_template: 'NGINX Ingress Controller {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'
