// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AllowListEntryApplyConfiguration represents a declarative configuration of the AllowListEntry type for use
// with apply.
//
// AllowListEntry represents an IP address and a subnet mask.
type AllowListEntryApplyConfiguration struct {
	IPWithMask *string `json:"ipWithMask,omitempty"`
}

// AllowListEntryApplyConfiguration constructs a declarative configuration of the AllowListEntry type for use with
// apply.
func AllowListEntry() *AllowListEntryApplyConfiguration {
	return &AllowListEntryApplyConfiguration{}
}

// WithIPWithMask sets the IPWithMask field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPWithMask field is set to the value of the last call.
func (b *AllowListEntryApplyConfiguration) WithIPWithMask(value string) *AllowListEntryApplyConfiguration {
	b.IPWithMask = &value
	return b
}
