// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// ApDosMonitorApplyConfiguration represents a declarative configuration of the ApDosMonitor type for use
// with apply.
//
// ApDosMonitor is how NGINX App Protect DoS monitors the stress level of the protected object. The monitor requests are sent from localhost (127.0.0.1). Default value: URI - None, protocol - http1, timeout - NGINX App Protect DoS default.
type ApDosMonitorApplyConfiguration struct {
	// URI is the destination to the desired protected object in the nginx.conf:
	URI *string `json:"uri,omitempty"`
	// Protocol determines if the server listens on http1 / http2 / grpc / websocket. The default is http1.
	Protocol *string `json:"protocol,omitempty"`
	// Timeout determines how long (in seconds) should NGINX App Protect DoS wait for a response. Default is 10 seconds for http1/http2 and 5 seconds for grpc.
	Timeout *uint64 `json:"timeout,omitempty"`
}

// ApDosMonitorApplyConfiguration constructs a declarative configuration of the ApDosMonitor type for use with
// apply.
func ApDosMonitor() *ApDosMonitorApplyConfiguration {
	return &ApDosMonitorApplyConfiguration{}
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *ApDosMonitorApplyConfiguration) WithURI(value string) *ApDosMonitorApplyConfiguration {
	b.URI = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ApDosMonitorApplyConfiguration) WithProtocol(value string) *ApDosMonitorApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *ApDosMonitorApplyConfiguration) WithTimeout(value uint64) *ApDosMonitorApplyConfiguration {
	b.Timeout = &value
	return b
}
