// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// DosProtectedResourceSpecApplyConfiguration represents a declarative configuration of the DosProtectedResourceSpec type for use
// with apply.
//
// DosProtectedResourceSpec defines the properties and values a DosProtectedResource can have.
type DosProtectedResourceSpecApplyConfiguration struct {
	// Enable enables the DOS feature if set to true
	Enable *bool `json:"enable,omitempty"`
	// Name is the name of protected object, max of 63 characters.
	Name         *string                         `json:"name,omitempty"`
	ApDosMonitor *ApDosMonitorApplyConfiguration `json:"apDosMonitor,omitempty"`
	// DosAccessLogDest is the network address for the access logs
	DosAccessLogDest *string `json:"dosAccessLogDest,omitempty"`
	// ApDosPolicy is the namespace/name of a ApDosPolicy resource
	ApDosPolicy    *string                           `json:"apDosPolicy,omitempty"`
	DosSecurityLog *DosSecurityLogApplyConfiguration `json:"dosSecurityLog,omitempty"`
	// AllowList is a list of allowed IPs and subnet masks
	AllowList []AllowListEntryApplyConfiguration `json:"allowList,omitempty"`
}

// DosProtectedResourceSpecApplyConfiguration constructs a declarative configuration of the DosProtectedResourceSpec type for use with
// apply.
func DosProtectedResourceSpec() *DosProtectedResourceSpecApplyConfiguration {
	return &DosProtectedResourceSpecApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *DosProtectedResourceSpecApplyConfiguration) WithEnable(value bool) *DosProtectedResourceSpecApplyConfiguration {
	b.Enable = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DosProtectedResourceSpecApplyConfiguration) WithName(value string) *DosProtectedResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithApDosMonitor sets the ApDosMonitor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApDosMonitor field is set to the value of the last call.
func (b *DosProtectedResourceSpecApplyConfiguration) WithApDosMonitor(value *ApDosMonitorApplyConfiguration) *DosProtectedResourceSpecApplyConfiguration {
	b.ApDosMonitor = value
	return b
}

// WithDosAccessLogDest sets the DosAccessLogDest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DosAccessLogDest field is set to the value of the last call.
func (b *DosProtectedResourceSpecApplyConfiguration) WithDosAccessLogDest(value string) *DosProtectedResourceSpecApplyConfiguration {
	b.DosAccessLogDest = &value
	return b
}

// WithApDosPolicy sets the ApDosPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApDosPolicy field is set to the value of the last call.
func (b *DosProtectedResourceSpecApplyConfiguration) WithApDosPolicy(value string) *DosProtectedResourceSpecApplyConfiguration {
	b.ApDosPolicy = &value
	return b
}

// WithDosSecurityLog sets the DosSecurityLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DosSecurityLog field is set to the value of the last call.
func (b *DosProtectedResourceSpecApplyConfiguration) WithDosSecurityLog(value *DosSecurityLogApplyConfiguration) *DosProtectedResourceSpecApplyConfiguration {
	b.DosSecurityLog = value
	return b
}

// WithAllowList adds the given value to the AllowList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowList field.
func (b *DosProtectedResourceSpecApplyConfiguration) WithAllowList(values ...*AllowListEntryApplyConfiguration) *DosProtectedResourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllowList")
		}
		b.AllowList = append(b.AllowList, *values[i])
	}
	return b
}
