// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// DosSecurityLogApplyConfiguration represents a declarative configuration of the DosSecurityLog type for use
// with apply.
//
// DosSecurityLog defines the security log of the DosProtectedResource.
type DosSecurityLogApplyConfiguration struct {
	// Enable enables the security logging feature if set to true
	Enable *bool `json:"enable,omitempty"`
	// ApDosLogConf is the namespace/name of a APDosLogConf resource
	ApDosLogConf *string `json:"apDosLogConf,omitempty"`
	// DosLogDest is the network address of a logging service, can be either IP or DNS name.
	DosLogDest *string `json:"dosLogDest,omitempty"`
}

// DosSecurityLogApplyConfiguration constructs a declarative configuration of the DosSecurityLog type for use with
// apply.
func DosSecurityLog() *DosSecurityLogApplyConfiguration {
	return &DosSecurityLogApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *DosSecurityLogApplyConfiguration) WithEnable(value bool) *DosSecurityLogApplyConfiguration {
	b.Enable = &value
	return b
}

// WithApDosLogConf sets the ApDosLogConf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApDosLogConf field is set to the value of the last call.
func (b *DosSecurityLogApplyConfiguration) WithApDosLogConf(value string) *DosSecurityLogApplyConfiguration {
	b.ApDosLogConf = &value
	return b
}

// WithDosLogDest sets the DosLogDest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DosLogDest field is set to the value of the last call.
func (b *DosSecurityLogApplyConfiguration) WithDosLogDest(value string) *DosSecurityLogApplyConfiguration {
	b.DosLogDest = &value
	return b
}
