// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1"
	configurationv1 "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned/typed/configuration/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakePolicies implements PolicyInterface
type fakePolicies struct {
	*gentype.FakeClientWithList[*v1.Policy, *v1.PolicyList]
	Fake *FakeK8sV1
}

func newFakePolicies(fake *FakeK8sV1, namespace string) configurationv1.PolicyInterface {
	return &fakePolicies{
		gentype.NewFakeClientWithList[*v1.Policy, *v1.PolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("policies"),
			v1.SchemeGroupVersion.WithKind("Policy"),
			func() *v1.Policy { return &v1.Policy{} },
			func() *v1.PolicyList { return &v1.PolicyList{} },
			func(dst, src *v1.PolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PolicyList) []*v1.Policy { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.PolicyList, items []*v1.Policy) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
