// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/nginx/kubernetes-ingress/pkg/apis/configuration/v1"
	configurationv1 "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/configuration/v1"
	typedconfigurationv1 "github.com/nginx/kubernetes-ingress/pkg/client/clientset/versioned/typed/configuration/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVirtualServerRoutes implements VirtualServerRouteInterface
type fakeVirtualServerRoutes struct {
	*gentype.FakeClientWithListAndApply[*v1.VirtualServerRoute, *v1.VirtualServerRouteList, *configurationv1.VirtualServerRouteApplyConfiguration]
	Fake *FakeK8sV1
}

func newFakeVirtualServerRoutes(fake *FakeK8sV1, namespace string) typedconfigurationv1.VirtualServerRouteInterface {
	return &fakeVirtualServerRoutes{
		gentype.NewFakeClientWithListAndApply[*v1.VirtualServerRoute, *v1.VirtualServerRouteList, *configurationv1.VirtualServerRouteApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("virtualserverroutes"),
			v1.SchemeGroupVersion.WithKind("VirtualServerRoute"),
			func() *v1.VirtualServerRoute { return &v1.VirtualServerRoute{} },
			func() *v1.VirtualServerRouteList { return &v1.VirtualServerRouteList{} },
			func(dst, src *v1.VirtualServerRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1.VirtualServerRouteList) []*v1.VirtualServerRoute {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.VirtualServerRouteList, items []*v1.VirtualServerRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
