// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1"
	configurationv1 "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned/typed/configuration/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGlobalConfigurations implements GlobalConfigurationInterface
type fakeGlobalConfigurations struct {
	*gentype.FakeClientWithList[*v1.GlobalConfiguration, *v1.GlobalConfigurationList]
	Fake *FakeK8sV1
}

func newFakeGlobalConfigurations(fake *FakeK8sV1, namespace string) configurationv1.GlobalConfigurationInterface {
	return &fakeGlobalConfigurations{
		gentype.NewFakeClientWithList[*v1.GlobalConfiguration, *v1.GlobalConfigurationList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("globalconfigurations"),
			v1.SchemeGroupVersion.WithKind("GlobalConfiguration"),
			func() *v1.GlobalConfiguration { return &v1.GlobalConfiguration{} },
			func() *v1.GlobalConfigurationList { return &v1.GlobalConfigurationList{} },
			func(dst, src *v1.GlobalConfigurationList) { dst.ListMeta = src.ListMeta },
			func(list *v1.GlobalConfigurationList) []*v1.GlobalConfiguration {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.GlobalConfigurationList, items []*v1.GlobalConfiguration) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
