// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// TransportServerLister helps list TransportServers.
// All objects returned here must be treated as read-only.
type TransportServerLister interface {
	// List lists all TransportServers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TransportServer, err error)
	// TransportServers returns an object that can list and get TransportServers.
	TransportServers(namespace string) TransportServerNamespaceLister
	TransportServerListerExpansion
}

// transportServerLister implements the TransportServerLister interface.
type transportServerLister struct {
	listers.ResourceIndexer[*v1alpha1.TransportServer]
}

// NewTransportServerLister returns a new TransportServerLister.
func NewTransportServerLister(indexer cache.Indexer) TransportServerLister {
	return &transportServerLister{listers.New[*v1alpha1.TransportServer](indexer, v1alpha1.Resource("transportserver"))}
}

// TransportServers returns an object that can list and get TransportServers.
func (s *transportServerLister) TransportServers(namespace string) TransportServerNamespaceLister {
	return transportServerNamespaceLister{listers.NewNamespaced[*v1alpha1.TransportServer](s.ResourceIndexer, namespace)}
}

// TransportServerNamespaceLister helps list and get TransportServers.
// All objects returned here must be treated as read-only.
type TransportServerNamespaceLister interface {
	// List lists all TransportServers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TransportServer, err error)
	// Get retrieves the TransportServer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TransportServer, error)
	TransportServerNamespaceListerExpansion
}

// transportServerNamespaceLister implements the TransportServerNamespaceLister
// interface.
type transportServerNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.TransportServer]
}
