// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AccessControlApplyConfiguration represents a declarative configuration of the AccessControl type for use
// with apply.
//
// AccessControl defines an access policy based on the source IP of a request.
type AccessControlApplyConfiguration struct {
	Allow []string `json:"allow,omitempty"`
	Deny  []string `json:"deny,omitempty"`
}

// AccessControlApplyConfiguration constructs a declarative configuration of the AccessControl type for use with
// apply.
func AccessControl() *AccessControlApplyConfiguration {
	return &AccessControlApplyConfiguration{}
}

// WithAllow adds the given value to the Allow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Allow field.
func (b *AccessControlApplyConfiguration) WithAllow(values ...string) *AccessControlApplyConfiguration {
	for i := range values {
		b.Allow = append(b.Allow, values[i])
	}
	return b
}

// WithDeny adds the given value to the Deny field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Deny field.
func (b *AccessControlApplyConfiguration) WithDeny(values ...string) *AccessControlApplyConfiguration {
	for i := range values {
		b.Deny = append(b.Deny, values[i])
	}
	return b
}
