// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ActionApplyConfiguration represents a declarative configuration of the Action type for use
// with apply.
//
// Action defines an action.
type ActionApplyConfiguration struct {
	// Passes requests to an upstream. The upstream with that name must be defined in the resource.
	Pass *string `json:"pass,omitempty"`
	// Redirects requests to a provided URL.
	Redirect *ActionRedirectApplyConfiguration `json:"redirect,omitempty"`
	// Returns a preconfigured response.
	Return *ActionReturnApplyConfiguration `json:"return,omitempty"`
	// Passes requests to an upstream with the ability to modify the request/response (for example, rewrite the URI or modify the headers).
	Proxy *ActionProxyApplyConfiguration `json:"proxy,omitempty"`
}

// ActionApplyConfiguration constructs a declarative configuration of the Action type for use with
// apply.
func Action() *ActionApplyConfiguration {
	return &ActionApplyConfiguration{}
}

// WithPass sets the Pass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pass field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithPass(value string) *ActionApplyConfiguration {
	b.Pass = &value
	return b
}

// WithRedirect sets the Redirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redirect field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithRedirect(value *ActionRedirectApplyConfiguration) *ActionApplyConfiguration {
	b.Redirect = value
	return b
}

// WithReturn sets the Return field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Return field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithReturn(value *ActionReturnApplyConfiguration) *ActionApplyConfiguration {
	b.Return = value
	return b
}

// WithProxy sets the Proxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Proxy field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithProxy(value *ActionProxyApplyConfiguration) *ActionApplyConfiguration {
	b.Proxy = value
	return b
}
