// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ActionReturnApplyConfiguration represents a declarative configuration of the ActionReturn type for use
// with apply.
//
// ActionReturn defines a return in an Action.
type ActionReturnApplyConfiguration struct {
	// The status code of the response. The allowed values are: 2XX, 4XX or 5XX. The default is 200.
	Code *int `json:"code,omitempty"`
	// The MIME type of the response. The default is text/plain.
	Type *string `json:"type,omitempty"`
	// The body of the response. Supports NGINX variables*. Variables must be enclosed in curly brackets. For example: Request is ${request_uri}\n.
	Body *string `json:"body,omitempty"`
	// The custom headers of the response.
	Headers []HeaderApplyConfiguration `json:"headers,omitempty"`
}

// ActionReturnApplyConfiguration constructs a declarative configuration of the ActionReturn type for use with
// apply.
func ActionReturn() *ActionReturnApplyConfiguration {
	return &ActionReturnApplyConfiguration{}
}

// WithCode sets the Code field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Code field is set to the value of the last call.
func (b *ActionReturnApplyConfiguration) WithCode(value int) *ActionReturnApplyConfiguration {
	b.Code = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ActionReturnApplyConfiguration) WithType(value string) *ActionReturnApplyConfiguration {
	b.Type = &value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *ActionReturnApplyConfiguration) WithBody(value string) *ActionReturnApplyConfiguration {
	b.Body = &value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *ActionReturnApplyConfiguration) WithHeaders(values ...*HeaderApplyConfiguration) *ActionReturnApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}
