// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ActionProxyApplyConfiguration represents a declarative configuration of the ActionProxy type for use
// with apply.
//
// ActionProxy defines a proxy in an Action.
type ActionProxyApplyConfiguration struct {
	// The name of the upstream which the requests will be proxied to. The upstream with that name must be defined in the resource.
	Upstream *string `json:"upstream,omitempty"`
	// The rewritten URI. If the route path is a regular expression – starts with ~ – the rewritePath can include capture groups with $1-9. For example $1 for the first group, and so on. For more information, check the rewrite example.
	RewritePath *string `json:"rewritePath,omitempty"`
	// The request headers modifications.
	RequestHeaders *ProxyRequestHeadersApplyConfiguration `json:"requestHeaders,omitempty"`
	// The response headers modifications.
	ResponseHeaders *ProxyResponseHeadersApplyConfiguration `json:"responseHeaders,omitempty"`
}

// ActionProxyApplyConfiguration constructs a declarative configuration of the ActionProxy type for use with
// apply.
func ActionProxy() *ActionProxyApplyConfiguration {
	return &ActionProxyApplyConfiguration{}
}

// WithUpstream sets the Upstream field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Upstream field is set to the value of the last call.
func (b *ActionProxyApplyConfiguration) WithUpstream(value string) *ActionProxyApplyConfiguration {
	b.Upstream = &value
	return b
}

// WithRewritePath sets the RewritePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RewritePath field is set to the value of the last call.
func (b *ActionProxyApplyConfiguration) WithRewritePath(value string) *ActionProxyApplyConfiguration {
	b.RewritePath = &value
	return b
}

// WithRequestHeaders sets the RequestHeaders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestHeaders field is set to the value of the last call.
func (b *ActionProxyApplyConfiguration) WithRequestHeaders(value *ProxyRequestHeadersApplyConfiguration) *ActionProxyApplyConfiguration {
	b.RequestHeaders = value
	return b
}

// WithResponseHeaders sets the ResponseHeaders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResponseHeaders field is set to the value of the last call.
func (b *ActionProxyApplyConfiguration) WithResponseHeaders(value *ProxyResponseHeadersApplyConfiguration) *ActionProxyApplyConfiguration {
	b.ResponseHeaders = value
	return b
}
