// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AddHeaderApplyConfiguration represents a declarative configuration of the AddHeader type for use
// with apply.
//
// AddHeader defines an HTTP Header with an optional Always field to use with the add_header NGINX directive.
type AddHeaderApplyConfiguration struct {
	HeaderApplyConfiguration `json:",inline"`
	// If set to true, add the header regardless of the response status code**. Default is false.
	Always *bool `json:"always,omitempty"`
}

// AddHeaderApplyConfiguration constructs a declarative configuration of the AddHeader type for use with
// apply.
func AddHeader() *AddHeaderApplyConfiguration {
	return &AddHeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AddHeaderApplyConfiguration) WithName(value string) *AddHeaderApplyConfiguration {
	b.HeaderApplyConfiguration.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *AddHeaderApplyConfiguration) WithValue(value string) *AddHeaderApplyConfiguration {
	b.HeaderApplyConfiguration.Value = &value
	return b
}

// WithAlways sets the Always field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Always field is set to the value of the last call.
func (b *AddHeaderApplyConfiguration) WithAlways(value bool) *AddHeaderApplyConfiguration {
	b.Always = &value
	return b
}
