// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// APIKeyApplyConfiguration represents a declarative configuration of the APIKey type for use
// with apply.
//
// The APIKey policy configures NGINX to authorize requests which provide a valid API Key in a specified header or query param.
type APIKeyApplyConfiguration struct {
	// The location of the API Key. For example, $http_auth, $arg_apikey, $cookie_auth. Accepted variables are $http_, $arg_, $cookie_.
	SuppliedIn *SuppliedInApplyConfiguration `json:"suppliedIn,omitempty"`
	// The key to which the API key is applied. Can contain text, variables, or a combination of them. Accepted variables are $http_, $arg_, $cookie_.
	ClientSecret *string `json:"clientSecret,omitempty"`
}

// APIKeyApplyConfiguration constructs a declarative configuration of the APIKey type for use with
// apply.
func APIKey() *APIKeyApplyConfiguration {
	return &APIKeyApplyConfiguration{}
}

// WithSuppliedIn sets the SuppliedIn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuppliedIn field is set to the value of the last call.
func (b *APIKeyApplyConfiguration) WithSuppliedIn(value *SuppliedInApplyConfiguration) *APIKeyApplyConfiguration {
	b.SuppliedIn = value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *APIKeyApplyConfiguration) WithClientSecret(value string) *APIKeyApplyConfiguration {
	b.ClientSecret = &value
	return b
}
