// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BasicAuthApplyConfiguration represents a declarative configuration of the BasicAuth type for use
// with apply.
//
// BasicAuth holds HTTP Basic authentication configuration
type BasicAuthApplyConfiguration struct {
	// The realm for the basic authentication.
	Realm *string `json:"realm,omitempty"`
	// The name of the Kubernetes secret that stores the Htpasswd configuration. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/htpasswd, and the config must be stored in the secret under the key htpasswd, otherwise the secret will be rejected as invalid.
	Secret *string `json:"secret,omitempty"`
}

// BasicAuthApplyConfiguration constructs a declarative configuration of the BasicAuth type for use with
// apply.
func BasicAuth() *BasicAuthApplyConfiguration {
	return &BasicAuthApplyConfiguration{}
}

// WithRealm sets the Realm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Realm field is set to the value of the last call.
func (b *BasicAuthApplyConfiguration) WithRealm(value string) *BasicAuthApplyConfiguration {
	b.Realm = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *BasicAuthApplyConfiguration) WithSecret(value string) *BasicAuthApplyConfiguration {
	b.Secret = &value
	return b
}
