// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CacheConditionsApplyConfiguration represents a declarative configuration of the CacheConditions type for use
// with apply.
//
// CacheConditions defines conditions for cache bypass and no-cache behavior.
// These use NGINX variables to make dynamic caching decisions based on request characteristics.
type CacheConditionsApplyConfiguration struct {
	// NoCache defines conditions under which the response will not be saved to a cache (proxy_no_cache).
	// If at least one value of the string parameters is not empty and is not equal to "0" then the response will not be saved.
	NoCache []string `json:"noCache,omitempty"`
	// Bypass defines conditions under which the response will not be taken from a cache (proxy_cache_bypass).
	// If at least one value of the string parameters is not empty and is not equal to "0" then the response will not be taken from the cache.
	Bypass []string `json:"bypass,omitempty"`
}

// CacheConditionsApplyConfiguration constructs a declarative configuration of the CacheConditions type for use with
// apply.
func CacheConditions() *CacheConditionsApplyConfiguration {
	return &CacheConditionsApplyConfiguration{}
}

// WithNoCache adds the given value to the NoCache field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NoCache field.
func (b *CacheConditionsApplyConfiguration) WithNoCache(values ...string) *CacheConditionsApplyConfiguration {
	for i := range values {
		b.NoCache = append(b.NoCache, values[i])
	}
	return b
}

// WithBypass adds the given value to the Bypass field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Bypass field.
func (b *CacheConditionsApplyConfiguration) WithBypass(values ...string) *CacheConditionsApplyConfiguration {
	for i := range values {
		b.Bypass = append(b.Bypass, values[i])
	}
	return b
}
