// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// CacheApplyConfiguration represents a declarative configuration of the Cache type for use
// with apply.
//
// Cache defines a cache policy for proxy caching.
type CacheApplyConfiguration struct {
	// CacheZoneName defines the name of the cache zone. Must start with a lowercase letter,
	// followed by alphanumeric characters or underscores, and end with an alphanumeric character.
	// Single lowercase letters are also allowed. Examples: "cache", "my_cache", "cache1".
	CacheZoneName *string `json:"cacheZoneName,omitempty"`
	// CacheZoneSize defines the size of the cache zone. Must be a number followed by a size unit:
	// 'k' or 'K' for kilobytes, 'm' or 'M' for megabytes, or 'g' or 'G' for gigabytes.
	// Examples: "10m", "1g", "512k".
	CacheZoneSize *string `json:"cacheZoneSize,omitempty"`
	// AllowedCodes defines which HTTP response codes should be cached.
	// Accepts either:
	// - The string "any" to cache all response codes (must be the only element)
	// - A list of HTTP status codes as integers (100-599)
	// Examples: ["any"], [200, 301, 404], [200].
	// Invalid: ["any", 200] (cannot mix "any" with specific codes).
	AllowedCodes []intstr.IntOrString `json:"allowedCodes,omitempty"`
	// AllowedMethods defines which HTTP methods should be cached.
	// Only "GET", "HEAD", and "POST" are supported by NGINX proxy_cache_methods directive.
	// GET and HEAD are always cached by default even if not specified.
	// Maximum of 3 items allowed. Examples: ["GET"], ["GET", "HEAD", "POST"].
	// Invalid methods: PUT, DELETE, PATCH, etc.
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	// Time defines the default cache time. Required when allowedCodes is specified.
	// Must be a number followed by a time unit:
	// 's' for seconds, 'm' for minutes, 'h' for hours, 'd' for days.
	// Examples: "30s", "5m", "1h", "2d".
	Time *string `json:"time,omitempty"`
	// CachePurgeAllow defines IP addresses or CIDR blocks allowed to purge cache.
	// This feature is only available in NGINX Plus.
	// Examples: ["192.168.1.100", "10.0.0.0/8", "::1"].
	// Invalid in NGINX OSS (will be ignored).
	CachePurgeAllow []string `json:"cachePurgeAllow,omitempty"`
	// OverrideUpstreamCache controls whether to override upstream cache headers
	// (using proxy_ignore_headers directive). When true, NGINX will ignore
	// cache-related headers from upstream servers like Cache-Control, Expires, etc.
	// Default: false.
	OverrideUpstreamCache *bool `json:"overrideUpstreamCache,omitempty"`
	// Levels defines the cache directory hierarchy levels for storing cached files.
	// Must be in format "X:Y" or "X:Y:Z" where X, Y, Z are either 1 or 2.
	// This controls the number of subdirectory levels and their name lengths.
	// Examples: "1:2", "2:2", "1:2:2".
	// Invalid: "3:1", "1:3", "1:2:3".
	Levels *string `json:"levels,omitempty"`
	// Inactive sets the time after which cached data that are not accessed get removed from the cache (inactive parameter).
	// By default, inactive is set to 10 minutes.
	Inactive *string `json:"inactive,omitempty"`
	// UseTempPath controls whether temporary files and the cache are put on different file systems (use_temp_path parameter).
	// If set to false, temporary files will be put directly in the cache directory (use_temp_path=off).
	// Default: false (use_temp_path=off, which puts temp files directly in cache directory for better performance).
	UseTempPath *bool `json:"useTempPath,omitempty"`
	// MaxSize sets the maximum cache size (max_size parameter).
	// When the size is exceeded, the cache manager removes the least recently used data.
	MaxSize *string `json:"maxSize,omitempty"`
	// MinFree sets the minimum amount of free space required on the file system with cache (min_free parameter).
	// When there is not enough free space, the cache manager removes the least recently used data.
	MinFree *string `json:"minFree,omitempty"`
	// Manager configures the cache manager process parameters (manager_files, manager_sleep, manager_threshold).
	Manager *CacheManagerApplyConfiguration `json:"manager,omitempty"`
	// CacheKey defines a key for caching (proxy_cache_key).
	// By default, close to "$scheme$proxy_host$uri$is_args$args".
	// Must not contain command execution patterns: $(, `, ;, &&, ||
	CacheKey *string `json:"cacheKey,omitempty"`
	// CacheUseStale determines in which cases a stale cached response can be used (proxy_cache_use_stale).
	// Valid parameters: error, timeout, invalid_header, updating, http_500, http_502, http_503, http_504, http_403, http_404, http_429, off.
	CacheUseStale []string `json:"cacheUseStale,omitempty"`
	// CacheRevalidate enables revalidation of expired cache items using conditional requests (proxy_cache_revalidate).
	// Uses "If-Modified-Since" and "If-None-Match" header fields.
	CacheRevalidate *bool `json:"cacheRevalidate,omitempty"`
	// CacheBackgroundUpdate allows starting a background subrequest to update an expired cache item (proxy_cache_background_update).
	// A stale cached response is returned to the client while the cache is being updated.
	CacheBackgroundUpdate *bool `json:"cacheBackgroundUpdate,omitempty"`
	// CacheMinUses sets the number of requests after which the response will be cached (proxy_cache_min_uses).
	CacheMinUses *int `json:"cacheMinUses,omitempty"`
	// Lock configures cache locking to prevent multiple identical requests from populating the same cache element simultaneously.
	Lock *CacheLockApplyConfiguration `json:"lock,omitempty"`
	// Conditions defines when responses should not be cached or taken from cache.
	Conditions *CacheConditionsApplyConfiguration `json:"conditions,omitempty"`
}

// CacheApplyConfiguration constructs a declarative configuration of the Cache type for use with
// apply.
func Cache() *CacheApplyConfiguration {
	return &CacheApplyConfiguration{}
}

// WithCacheZoneName sets the CacheZoneName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheZoneName field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithCacheZoneName(value string) *CacheApplyConfiguration {
	b.CacheZoneName = &value
	return b
}

// WithCacheZoneSize sets the CacheZoneSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheZoneSize field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithCacheZoneSize(value string) *CacheApplyConfiguration {
	b.CacheZoneSize = &value
	return b
}

// WithAllowedCodes adds the given value to the AllowedCodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedCodes field.
func (b *CacheApplyConfiguration) WithAllowedCodes(values ...intstr.IntOrString) *CacheApplyConfiguration {
	for i := range values {
		b.AllowedCodes = append(b.AllowedCodes, values[i])
	}
	return b
}

// WithAllowedMethods adds the given value to the AllowedMethods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedMethods field.
func (b *CacheApplyConfiguration) WithAllowedMethods(values ...string) *CacheApplyConfiguration {
	for i := range values {
		b.AllowedMethods = append(b.AllowedMethods, values[i])
	}
	return b
}

// WithTime sets the Time field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Time field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithTime(value string) *CacheApplyConfiguration {
	b.Time = &value
	return b
}

// WithCachePurgeAllow adds the given value to the CachePurgeAllow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CachePurgeAllow field.
func (b *CacheApplyConfiguration) WithCachePurgeAllow(values ...string) *CacheApplyConfiguration {
	for i := range values {
		b.CachePurgeAllow = append(b.CachePurgeAllow, values[i])
	}
	return b
}

// WithOverrideUpstreamCache sets the OverrideUpstreamCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OverrideUpstreamCache field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithOverrideUpstreamCache(value bool) *CacheApplyConfiguration {
	b.OverrideUpstreamCache = &value
	return b
}

// WithLevels sets the Levels field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Levels field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithLevels(value string) *CacheApplyConfiguration {
	b.Levels = &value
	return b
}

// WithInactive sets the Inactive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Inactive field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithInactive(value string) *CacheApplyConfiguration {
	b.Inactive = &value
	return b
}

// WithUseTempPath sets the UseTempPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseTempPath field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithUseTempPath(value bool) *CacheApplyConfiguration {
	b.UseTempPath = &value
	return b
}

// WithMaxSize sets the MaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSize field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithMaxSize(value string) *CacheApplyConfiguration {
	b.MaxSize = &value
	return b
}

// WithMinFree sets the MinFree field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinFree field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithMinFree(value string) *CacheApplyConfiguration {
	b.MinFree = &value
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithManager(value *CacheManagerApplyConfiguration) *CacheApplyConfiguration {
	b.Manager = value
	return b
}

// WithCacheKey sets the CacheKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheKey field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithCacheKey(value string) *CacheApplyConfiguration {
	b.CacheKey = &value
	return b
}

// WithCacheUseStale adds the given value to the CacheUseStale field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CacheUseStale field.
func (b *CacheApplyConfiguration) WithCacheUseStale(values ...string) *CacheApplyConfiguration {
	for i := range values {
		b.CacheUseStale = append(b.CacheUseStale, values[i])
	}
	return b
}

// WithCacheRevalidate sets the CacheRevalidate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheRevalidate field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithCacheRevalidate(value bool) *CacheApplyConfiguration {
	b.CacheRevalidate = &value
	return b
}

// WithCacheBackgroundUpdate sets the CacheBackgroundUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheBackgroundUpdate field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithCacheBackgroundUpdate(value bool) *CacheApplyConfiguration {
	b.CacheBackgroundUpdate = &value
	return b
}

// WithCacheMinUses sets the CacheMinUses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheMinUses field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithCacheMinUses(value int) *CacheApplyConfiguration {
	b.CacheMinUses = &value
	return b
}

// WithLock sets the Lock field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lock field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithLock(value *CacheLockApplyConfiguration) *CacheApplyConfiguration {
	b.Lock = value
	return b
}

// WithConditions sets the Conditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conditions field is set to the value of the last call.
func (b *CacheApplyConfiguration) WithConditions(value *CacheConditionsApplyConfiguration) *CacheApplyConfiguration {
	b.Conditions = value
	return b
}
