// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CacheLockApplyConfiguration represents a declarative configuration of the CacheLock type for use
// with apply.
//
// CacheLock defines cache locking parameters. When enabled, only one request at a time will be allowed to populate a new cache element.
// Other requests of the same cache element will either wait for a response to appear in the cache or the cache lock for this element to be released.
type CacheLockApplyConfiguration struct {
	// Enable sets whether cache locking is enabled (proxy_cache_lock).
	// When enabled, only one request at a time will be allowed to populate a new cache element according to the proxy_cache_key.
	Enable *bool `json:"enable,omitempty"`
	// Timeout sets a timeout for proxy_cache_lock.
	// When the time expires, the request will be passed to the proxied server, however, the response will not be cached.
	Timeout *string `json:"timeout,omitempty"`
	// Age sets the maximum time a cache lock can be held (proxy_cache_lock_age).
	// If the last request passed to the proxied server for populating a new cache element has not completed for the specified time, one more request may be passed.
	Age *string `json:"age,omitempty"`
}

// CacheLockApplyConfiguration constructs a declarative configuration of the CacheLock type for use with
// apply.
func CacheLock() *CacheLockApplyConfiguration {
	return &CacheLockApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *CacheLockApplyConfiguration) WithEnable(value bool) *CacheLockApplyConfiguration {
	b.Enable = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *CacheLockApplyConfiguration) WithTimeout(value string) *CacheLockApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithAge sets the Age field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Age field is set to the value of the last call.
func (b *CacheLockApplyConfiguration) WithAge(value string) *CacheLockApplyConfiguration {
	b.Age = &value
	return b
}
