// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CertManagerApplyConfiguration represents a declarative configuration of the CertManager type for use
// with apply.
//
// CertManager defines a cert manager config for a TLS.
type CertManagerApplyConfiguration struct {
	// the name of a ClusterIssuer. A ClusterIssuer is a cert-manager resource which describes the certificate authority capable of signing certificates. It does not matter which namespace your VirtualServer resides, as ClusterIssuers are non-namespaced resources. Please note that one of issuer and cluster-issuer are required, but they are mutually exclusive - one and only one must be defined.
	ClusterIssuer *string `json:"cluster-issuer,omitempty"`
	// the name of an Issuer. An Issuer is a cert-manager resource which describes the certificate authority capable of signing certificates. The Issuer must be in the same namespace as the VirtualServer resource. Please note that one of issuer and cluster-issuer are required, but they are mutually exclusive - one and only one must be defined.
	Issuer *string `json:"issuer,omitempty"`
	// The kind of the external issuer resource, for example AWSPCAIssuer. This is only necessary for out-of-tree issuers. This cannot be defined if cluster-issuer is also defined.
	IssuerKind *string `json:"issuer-kind,omitempty"`
	// The API group of the external issuer controller, for example awspca.cert-manager.io. This is only necessary for out-of-tree issuers. This cannot be defined if cluster-issuer is also defined.
	IssuerGroup *string `json:"issuer-group,omitempty"`
	// This field allows you to configure spec.commonName for the Certificate to be generated. This configuration adds a CN to the x509 certificate.
	CommonName *string `json:"common-name,omitempty"`
	// This field allows you to configure spec.duration field for the Certificate to be generated. Must be specified using a Go time.Duration string format, which does not allow the d (days) suffix. You must specify these values using s, m, and h suffixes instead.
	Duration *string `json:"duration,omitempty"`
	// this annotation allows you to configure spec.renewBefore field for the Certificate to be generated. Must be specified using a Go time.Duration string format, which does not allow the d (days) suffix. You must specify these values using s, m, and h suffixes instead.
	RenewBefore *string `json:"renew-before,omitempty"`
	// This field allows you to configure spec.usages field for the Certificate to be generated. Pass a string with comma-separated values i.e. key agreement,digital signature, server auth. An exhaustive list of supported key usages can be found in the the cert-manager api documentation.
	Usages *string `json:"usages,omitempty"`
	// When true, ask cert-manager for a temporary self-signed certificate pending the issuance of the Certificate. This allows HTTPS-only servers to use ACME HTTP01 challenges when the TLS secret does not exist yet.
	IssueTempCert *bool `json:"issue-temp-cert,omitempty"`
}

// CertManagerApplyConfiguration constructs a declarative configuration of the CertManager type for use with
// apply.
func CertManager() *CertManagerApplyConfiguration {
	return &CertManagerApplyConfiguration{}
}

// WithClusterIssuer sets the ClusterIssuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterIssuer field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithClusterIssuer(value string) *CertManagerApplyConfiguration {
	b.ClusterIssuer = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithIssuer(value string) *CertManagerApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithIssuerKind sets the IssuerKind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerKind field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithIssuerKind(value string) *CertManagerApplyConfiguration {
	b.IssuerKind = &value
	return b
}

// WithIssuerGroup sets the IssuerGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerGroup field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithIssuerGroup(value string) *CertManagerApplyConfiguration {
	b.IssuerGroup = &value
	return b
}

// WithCommonName sets the CommonName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommonName field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithCommonName(value string) *CertManagerApplyConfiguration {
	b.CommonName = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithDuration(value string) *CertManagerApplyConfiguration {
	b.Duration = &value
	return b
}

// WithRenewBefore sets the RenewBefore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewBefore field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithRenewBefore(value string) *CertManagerApplyConfiguration {
	b.RenewBefore = &value
	return b
}

// WithUsages sets the Usages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Usages field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithUsages(value string) *CertManagerApplyConfiguration {
	b.Usages = &value
	return b
}

// WithIssueTempCert sets the IssueTempCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssueTempCert field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithIssueTempCert(value bool) *CertManagerApplyConfiguration {
	b.IssueTempCert = &value
	return b
}
