// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ConditionApplyConfiguration represents a declarative configuration of the Condition type for use
// with apply.
//
// Condition defines a condition in a MatchRule.
type ConditionApplyConfiguration struct {
	// The name of a header. Must consist of alphanumeric characters or -.
	Header *string `json:"header,omitempty"`
	// The name of a cookie. Must consist of alphanumeric characters or _.
	Cookie *string `json:"cookie,omitempty"`
	// The name of an argument. Must consist of alphanumeric characters or _.
	Argument *string `json:"argument,omitempty"`
	// The name of an NGINX variable. Must start with $.
	Variable *string `json:"variable,omitempty"`
	// The value to match the condition against.
	Value *string `json:"value,omitempty"`
}

// ConditionApplyConfiguration constructs a declarative configuration of the Condition type for use with
// apply.
func Condition() *ConditionApplyConfiguration {
	return &ConditionApplyConfiguration{}
}

// WithHeader sets the Header field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Header field is set to the value of the last call.
func (b *ConditionApplyConfiguration) WithHeader(value string) *ConditionApplyConfiguration {
	b.Header = &value
	return b
}

// WithCookie sets the Cookie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cookie field is set to the value of the last call.
func (b *ConditionApplyConfiguration) WithCookie(value string) *ConditionApplyConfiguration {
	b.Cookie = &value
	return b
}

// WithArgument sets the Argument field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Argument field is set to the value of the last call.
func (b *ConditionApplyConfiguration) WithArgument(value string) *ConditionApplyConfiguration {
	b.Argument = &value
	return b
}

// WithVariable sets the Variable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Variable field is set to the value of the last call.
func (b *ConditionApplyConfiguration) WithVariable(value string) *ConditionApplyConfiguration {
	b.Variable = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ConditionApplyConfiguration) WithValue(value string) *ConditionApplyConfiguration {
	b.Value = &value
	return b
}
