// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EgressMTLSApplyConfiguration represents a declarative configuration of the EgressMTLS type for use
// with apply.
//
// The EgressMTLS policy configures upstreams authentication and certificate verification.
type EgressMTLSApplyConfiguration struct {
	// The name of the Kubernetes secret that stores the TLS certificate and key. It must be in the same namespace as the Policy resource. The secret must be of the type kubernetes.io/tls, the certificate must be stored in the secret under the key tls.crt, and the key must be stored under the key tls.key, otherwise the secret will be rejected as invalid.
	TLSSecret *string `json:"tlsSecret,omitempty"`
	// Enables verification of the upstream HTTPS server certificate.
	VerifyServer *bool `json:"verifyServer,omitempty"`
	// Sets the verification depth in the proxied HTTPS server certificates chain. The default is 1.
	VerifyDepth *int `json:"verifyDepth,omitempty"`
	// Specifies the protocols for requests to an upstream HTTPS server. The default is TLSv1 TLSv1.1 TLSv1.2.
	Protocols *string `json:"protocols,omitempty"`
	// Enables reuse of SSL sessions to the upstreams. The default is true.
	SessionReuse *bool `json:"sessionReuse,omitempty"`
	// Specifies the enabled ciphers for requests to an upstream HTTPS server. The default is DEFAULT.
	Ciphers *string `json:"ciphers,omitempty"`
	// The name of the Kubernetes secret that stores the CA certificate. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/ca, and the certificate must be stored in the secret under the key ca.crt, otherwise the secret will be rejected as invalid.
	TrustedCertSecret *string `json:"trustedCertSecret,omitempty"`
	// Enables passing of the server name through Server Name Indication extension.
	ServerName *bool `json:"serverName,omitempty"`
	// Allows overriding the server name used to verify the certificate of the upstream HTTPS server.
	SSLName *string `json:"sslName,omitempty"`
}

// EgressMTLSApplyConfiguration constructs a declarative configuration of the EgressMTLS type for use with
// apply.
func EgressMTLS() *EgressMTLSApplyConfiguration {
	return &EgressMTLSApplyConfiguration{}
}

// WithTLSSecret sets the TLSSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSSecret field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithTLSSecret(value string) *EgressMTLSApplyConfiguration {
	b.TLSSecret = &value
	return b
}

// WithVerifyServer sets the VerifyServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerifyServer field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithVerifyServer(value bool) *EgressMTLSApplyConfiguration {
	b.VerifyServer = &value
	return b
}

// WithVerifyDepth sets the VerifyDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerifyDepth field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithVerifyDepth(value int) *EgressMTLSApplyConfiguration {
	b.VerifyDepth = &value
	return b
}

// WithProtocols sets the Protocols field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocols field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithProtocols(value string) *EgressMTLSApplyConfiguration {
	b.Protocols = &value
	return b
}

// WithSessionReuse sets the SessionReuse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionReuse field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithSessionReuse(value bool) *EgressMTLSApplyConfiguration {
	b.SessionReuse = &value
	return b
}

// WithCiphers sets the Ciphers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ciphers field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithCiphers(value string) *EgressMTLSApplyConfiguration {
	b.Ciphers = &value
	return b
}

// WithTrustedCertSecret sets the TrustedCertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustedCertSecret field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithTrustedCertSecret(value string) *EgressMTLSApplyConfiguration {
	b.TrustedCertSecret = &value
	return b
}

// WithServerName sets the ServerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerName field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithServerName(value bool) *EgressMTLSApplyConfiguration {
	b.ServerName = &value
	return b
}

// WithSSLName sets the SSLName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLName field is set to the value of the last call.
func (b *EgressMTLSApplyConfiguration) WithSSLName(value string) *EgressMTLSApplyConfiguration {
	b.SSLName = &value
	return b
}
