// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ErrorPageReturnApplyConfiguration represents a declarative configuration of the ErrorPageReturn type for use
// with apply.
//
// ErrorPageReturn defines a return for an ErrorPage.
type ErrorPageReturnApplyConfiguration struct {
	ActionReturnApplyConfiguration `json:",inline"`
}

// ErrorPageReturnApplyConfiguration constructs a declarative configuration of the ErrorPageReturn type for use with
// apply.
func ErrorPageReturn() *ErrorPageReturnApplyConfiguration {
	return &ErrorPageReturnApplyConfiguration{}
}

// WithCode sets the Code field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Code field is set to the value of the last call.
func (b *ErrorPageReturnApplyConfiguration) WithCode(value int) *ErrorPageReturnApplyConfiguration {
	b.ActionReturnApplyConfiguration.Code = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ErrorPageReturnApplyConfiguration) WithType(value string) *ErrorPageReturnApplyConfiguration {
	b.ActionReturnApplyConfiguration.Type = &value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *ErrorPageReturnApplyConfiguration) WithBody(value string) *ErrorPageReturnApplyConfiguration {
	b.ActionReturnApplyConfiguration.Body = &value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *ErrorPageReturnApplyConfiguration) WithHeaders(values ...*HeaderApplyConfiguration) *ErrorPageReturnApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.ActionReturnApplyConfiguration.Headers = append(b.ActionReturnApplyConfiguration.Headers, *values[i])
	}
	return b
}
