// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ErrorPageApplyConfiguration represents a declarative configuration of the ErrorPage type for use
// with apply.
//
// ErrorPage defines an ErrorPage in a Route.
type ErrorPageApplyConfiguration struct {
	// A list of error status codes.
	Codes []int `json:"codes,omitempty"`
	// The redirect action for the given status codes.
	Return *ErrorPageReturnApplyConfiguration `json:"return,omitempty"`
	// The canned response action for the given status codes.
	Redirect *ErrorPageRedirectApplyConfiguration `json:"redirect,omitempty"`
}

// ErrorPageApplyConfiguration constructs a declarative configuration of the ErrorPage type for use with
// apply.
func ErrorPage() *ErrorPageApplyConfiguration {
	return &ErrorPageApplyConfiguration{}
}

// WithCodes adds the given value to the Codes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Codes field.
func (b *ErrorPageApplyConfiguration) WithCodes(values ...int) *ErrorPageApplyConfiguration {
	for i := range values {
		b.Codes = append(b.Codes, values[i])
	}
	return b
}

// WithReturn sets the Return field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Return field is set to the value of the last call.
func (b *ErrorPageApplyConfiguration) WithReturn(value *ErrorPageReturnApplyConfiguration) *ErrorPageApplyConfiguration {
	b.Return = value
	return b
}

// WithRedirect sets the Redirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redirect field is set to the value of the last call.
func (b *ErrorPageApplyConfiguration) WithRedirect(value *ErrorPageRedirectApplyConfiguration) *ErrorPageApplyConfiguration {
	b.Redirect = value
	return b
}
