// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ErrorPageRedirectApplyConfiguration represents a declarative configuration of the ErrorPageRedirect type for use
// with apply.
//
// ErrorPageRedirect defines a redirect for an ErrorPage.
type ErrorPageRedirectApplyConfiguration struct {
	ActionRedirectApplyConfiguration `json:",inline"`
}

// ErrorPageRedirectApplyConfiguration constructs a declarative configuration of the ErrorPageRedirect type for use with
// apply.
func ErrorPageRedirect() *ErrorPageRedirectApplyConfiguration {
	return &ErrorPageRedirectApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *ErrorPageRedirectApplyConfiguration) WithURL(value string) *ErrorPageRedirectApplyConfiguration {
	b.ActionRedirectApplyConfiguration.URL = &value
	return b
}

// WithCode sets the Code field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Code field is set to the value of the last call.
func (b *ErrorPageRedirectApplyConfiguration) WithCode(value int) *ErrorPageRedirectApplyConfiguration {
	b.ActionRedirectApplyConfiguration.Code = &value
	return b
}
