// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	configurationv1 "github.com/nginx/kubernetes-ingress/pkg/apis/configuration/v1"
)

// ExternalDNSApplyConfiguration represents a declarative configuration of the ExternalDNS type for use
// with apply.
//
// ExternalDNS defines externaldns sub-resource of a virtual server.
type ExternalDNSApplyConfiguration struct {
	// Enables ExternalDNS integration for a VirtualServer resource. The default is false.
	Enable *bool `json:"enable,omitempty"`
	// The record Type that should be created, e.g. “A”, “AAAA”, “CNAME”. This is automatically computed based on the external endpoints if not defined.
	RecordType *string `json:"recordType,omitempty"`
	// TTL for the DNS record. This defaults to 0 if not defined.
	RecordTTL *int64 `json:"recordTTL,omitempty"`
	// Configure labels to be applied to the Endpoint resources that will be consumed by ExternalDNS.
	Labels map[string]string `json:"labels,omitempty"`
	// Configure provider specific properties which holds the name and value of a configuration which is specific to individual DNS providers.
	ProviderSpecific *configurationv1.ProviderSpecific `json:"providerSpecific,omitempty"`
}

// ExternalDNSApplyConfiguration constructs a declarative configuration of the ExternalDNS type for use with
// apply.
func ExternalDNS() *ExternalDNSApplyConfiguration {
	return &ExternalDNSApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *ExternalDNSApplyConfiguration) WithEnable(value bool) *ExternalDNSApplyConfiguration {
	b.Enable = &value
	return b
}

// WithRecordType sets the RecordType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordType field is set to the value of the last call.
func (b *ExternalDNSApplyConfiguration) WithRecordType(value string) *ExternalDNSApplyConfiguration {
	b.RecordType = &value
	return b
}

// WithRecordTTL sets the RecordTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordTTL field is set to the value of the last call.
func (b *ExternalDNSApplyConfiguration) WithRecordTTL(value int64) *ExternalDNSApplyConfiguration {
	b.RecordTTL = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ExternalDNSApplyConfiguration) WithLabels(entries map[string]string) *ExternalDNSApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithProviderSpecific sets the ProviderSpecific field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSpecific field is set to the value of the last call.
func (b *ExternalDNSApplyConfiguration) WithProviderSpecific(value configurationv1.ProviderSpecific) *ExternalDNSApplyConfiguration {
	b.ProviderSpecific = &value
	return b
}
