// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ExternalEndpointApplyConfiguration represents a declarative configuration of the ExternalEndpoint type for use
// with apply.
//
// ExternalEndpoint defines the IP/ Hostname and ports used to connect to this resource.
type ExternalEndpointApplyConfiguration struct {
	IP       *string `json:"ip,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	Ports    *string `json:"ports,omitempty"`
}

// ExternalEndpointApplyConfiguration constructs a declarative configuration of the ExternalEndpoint type for use with
// apply.
func ExternalEndpoint() *ExternalEndpointApplyConfiguration {
	return &ExternalEndpointApplyConfiguration{}
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *ExternalEndpointApplyConfiguration) WithIP(value string) *ExternalEndpointApplyConfiguration {
	b.IP = &value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *ExternalEndpointApplyConfiguration) WithHostname(value string) *ExternalEndpointApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithPorts sets the Ports field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ports field is set to the value of the last call.
func (b *ExternalEndpointApplyConfiguration) WithPorts(value string) *ExternalEndpointApplyConfiguration {
	b.Ports = &value
	return b
}
