// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GlobalConfigurationSpecApplyConfiguration represents a declarative configuration of the GlobalConfigurationSpec type for use
// with apply.
//
// GlobalConfigurationSpec resource defines the global configuration parameters of the Ingress Controller.
type GlobalConfigurationSpecApplyConfiguration struct {
	// Listeners field of the GlobalConfigurationSpec resource
	Listeners []ListenerApplyConfiguration `json:"listeners,omitempty"`
}

// GlobalConfigurationSpecApplyConfiguration constructs a declarative configuration of the GlobalConfigurationSpec type for use with
// apply.
func GlobalConfigurationSpec() *GlobalConfigurationSpecApplyConfiguration {
	return &GlobalConfigurationSpecApplyConfiguration{}
}

// WithListeners adds the given value to the Listeners field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Listeners field.
func (b *GlobalConfigurationSpecApplyConfiguration) WithListeners(values ...*ListenerApplyConfiguration) *GlobalConfigurationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithListeners")
		}
		b.Listeners = append(b.Listeners, *values[i])
	}
	return b
}
