// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HeaderApplyConfiguration represents a declarative configuration of the Header type for use
// with apply.
//
// Header defines an HTTP Header.
type HeaderApplyConfiguration struct {
	// The name of the header.
	Name *string `json:"name,omitempty"`
	// The value of the header.
	Value *string `json:"value,omitempty"`
}

// HeaderApplyConfiguration constructs a declarative configuration of the Header type for use with
// apply.
func Header() *HeaderApplyConfiguration {
	return &HeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HeaderApplyConfiguration) WithName(value string) *HeaderApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *HeaderApplyConfiguration) WithValue(value string) *HeaderApplyConfiguration {
	b.Value = &value
	return b
}
