// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HealthCheckApplyConfiguration represents a declarative configuration of the HealthCheck type for use
// with apply.
//
// HealthCheck defines the parameters for active Upstream HealthChecks.
type HealthCheckApplyConfiguration struct {
	// Enables a health check for an upstream server. The default is false.
	Enable *bool `json:"enable,omitempty"`
	// The path used for health check requests. The default is /. This is not configurable for gRPC type upstreams.
	Path *string `json:"path,omitempty"`
	// The interval between two consecutive health checks. The default is 5s.
	Interval *string `json:"interval,omitempty"`
	// The time within which each health check will be randomly delayed. By default, there is no delay.
	Jitter *string `json:"jitter,omitempty"`
	// The number of consecutive failed health checks of a particular upstream server after which this server will be considered unhealthy. The default is 1.
	Fails *int `json:"fails,omitempty"`
	// The number of consecutive passed health checks of a particular upstream server after which the server will be considered healthy. The default is 1.
	Passes *int `json:"passes,omitempty"`
	// The port used for health check requests. By default, the server port is used. Note: in contrast with the port of the upstream, this port is not a service port, but a port of a pod.
	Port *int `json:"port,omitempty"`
	// The TLS configuration used for health check requests. By default, the tls field of the upstream is used.
	TLS *UpstreamTLSApplyConfiguration `json:"tls,omitempty"`
	// The timeout for establishing a connection with an upstream server. By default, the connect-timeout of the upstream is used.
	ConnectTimeout *string `json:"connect-timeout,omitempty"`
	// The timeout for reading a response from an upstream server. By default, the read-timeout of the upstream is used.
	ReadTimeout *string `json:"read-timeout,omitempty"`
	// The timeout for transmitting a request to an upstream server. By default, the send-timeout of the upstream is used.
	SendTimeout *string `json:"send-timeout,omitempty"`
	// The request headers used for health check requests. NGINX Plus always sets the Host, User-Agent and Connection headers for health check requests.
	Headers []HeaderApplyConfiguration `json:"headers,omitempty"`
	// The expected response status codes of a health check. By default, the response should have status code 2xx or 3xx. Examples: "200", "! 500", "301-303 307". This not supported for gRPC type upstreams.
	StatusMatch *string `json:"statusMatch,omitempty"`
	// The expected gRPC status code of the upstream server response to the Check method. Configure this field only if your gRPC services do not implement the gRPC health checking protocol. For example, configure 12 if the upstream server responds with 12 (UNIMPLEMENTED) status code. Only valid on gRPC type upstreams.
	GRPCStatus *int `json:"grpcStatus,omitempty"`
	// The gRPC service to be monitored on the upstream server. Only valid on gRPC type upstreams.
	GRPCService *string `json:"grpcService,omitempty"`
	// Require every newly added server to pass all configured health checks before NGINX Plus sends traffic to it. If this is not specified, or is set to false, the server will be initially considered healthy. When combined with slow-start, it gives a new server more time to connect to databases and “warm up” before being asked to handle their full share of traffic.
	Mandatory *bool `json:"mandatory,omitempty"`
	// Set the initial “up” state for a server after reload if the server was considered healthy before reload. Enabling persistent requires that the mandatory parameter is also set to true.
	Persistent *bool `json:"persistent,omitempty"`
	// Enables keepalive connections for health checks and specifies the time during which requests can be processed through one keepalive connection. The default is 60s.
	KeepaliveTime *string `json:"keepalive-time,omitempty"`
}

// HealthCheckApplyConfiguration constructs a declarative configuration of the HealthCheck type for use with
// apply.
func HealthCheck() *HealthCheckApplyConfiguration {
	return &HealthCheckApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithEnable(value bool) *HealthCheckApplyConfiguration {
	b.Enable = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithPath(value string) *HealthCheckApplyConfiguration {
	b.Path = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithInterval(value string) *HealthCheckApplyConfiguration {
	b.Interval = &value
	return b
}

// WithJitter sets the Jitter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Jitter field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithJitter(value string) *HealthCheckApplyConfiguration {
	b.Jitter = &value
	return b
}

// WithFails sets the Fails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fails field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithFails(value int) *HealthCheckApplyConfiguration {
	b.Fails = &value
	return b
}

// WithPasses sets the Passes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Passes field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithPasses(value int) *HealthCheckApplyConfiguration {
	b.Passes = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithPort(value int) *HealthCheckApplyConfiguration {
	b.Port = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithTLS(value *UpstreamTLSApplyConfiguration) *HealthCheckApplyConfiguration {
	b.TLS = value
	return b
}

// WithConnectTimeout sets the ConnectTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectTimeout field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithConnectTimeout(value string) *HealthCheckApplyConfiguration {
	b.ConnectTimeout = &value
	return b
}

// WithReadTimeout sets the ReadTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadTimeout field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithReadTimeout(value string) *HealthCheckApplyConfiguration {
	b.ReadTimeout = &value
	return b
}

// WithSendTimeout sets the SendTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SendTimeout field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithSendTimeout(value string) *HealthCheckApplyConfiguration {
	b.SendTimeout = &value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *HealthCheckApplyConfiguration) WithHeaders(values ...*HeaderApplyConfiguration) *HealthCheckApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}

// WithStatusMatch sets the StatusMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusMatch field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithStatusMatch(value string) *HealthCheckApplyConfiguration {
	b.StatusMatch = &value
	return b
}

// WithGRPCStatus sets the GRPCStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GRPCStatus field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithGRPCStatus(value int) *HealthCheckApplyConfiguration {
	b.GRPCStatus = &value
	return b
}

// WithGRPCService sets the GRPCService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GRPCService field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithGRPCService(value string) *HealthCheckApplyConfiguration {
	b.GRPCService = &value
	return b
}

// WithMandatory sets the Mandatory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mandatory field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithMandatory(value bool) *HealthCheckApplyConfiguration {
	b.Mandatory = &value
	return b
}

// WithPersistent sets the Persistent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Persistent field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithPersistent(value bool) *HealthCheckApplyConfiguration {
	b.Persistent = &value
	return b
}

// WithKeepaliveTime sets the KeepaliveTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepaliveTime field is set to the value of the last call.
func (b *HealthCheckApplyConfiguration) WithKeepaliveTime(value string) *HealthCheckApplyConfiguration {
	b.KeepaliveTime = &value
	return b
}
