// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IngressMTLSApplyConfiguration represents a declarative configuration of the IngressMTLS type for use
// with apply.
//
// The IngressMTLS policy configures client certificate verification.
type IngressMTLSApplyConfiguration struct {
	// The name of the Kubernetes secret that stores the CA certificate. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/ca, and the certificate must be stored in the secret under the key ca.crt, otherwise the secret will be rejected as invalid.
	ClientCertSecret *string `json:"clientCertSecret,omitempty"`
	// The file name of the Certificate Revocation List. NGINX Ingress Controller will look for this file in /etc/nginx/secrets
	CrlFileName *string `json:"crlFileName,omitempty"`
	// Verification for the client. Possible values are "on", "off", "optional", "optional_no_ca". The default is "on".
	VerifyClient *string `json:"verifyClient,omitempty"`
	// Sets the verification depth in the client certificates chain. The default is 1.
	VerifyDepth *int `json:"verifyDepth,omitempty"`
}

// IngressMTLSApplyConfiguration constructs a declarative configuration of the IngressMTLS type for use with
// apply.
func IngressMTLS() *IngressMTLSApplyConfiguration {
	return &IngressMTLSApplyConfiguration{}
}

// WithClientCertSecret sets the ClientCertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCertSecret field is set to the value of the last call.
func (b *IngressMTLSApplyConfiguration) WithClientCertSecret(value string) *IngressMTLSApplyConfiguration {
	b.ClientCertSecret = &value
	return b
}

// WithCrlFileName sets the CrlFileName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CrlFileName field is set to the value of the last call.
func (b *IngressMTLSApplyConfiguration) WithCrlFileName(value string) *IngressMTLSApplyConfiguration {
	b.CrlFileName = &value
	return b
}

// WithVerifyClient sets the VerifyClient field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerifyClient field is set to the value of the last call.
func (b *IngressMTLSApplyConfiguration) WithVerifyClient(value string) *IngressMTLSApplyConfiguration {
	b.VerifyClient = &value
	return b
}

// WithVerifyDepth sets the VerifyDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerifyDepth field is set to the value of the last call.
func (b *IngressMTLSApplyConfiguration) WithVerifyDepth(value int) *IngressMTLSApplyConfiguration {
	b.VerifyDepth = &value
	return b
}
