// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// JWTAuthApplyConfiguration represents a declarative configuration of the JWTAuth type for use
// with apply.
//
// JWTAuth holds JWT authentication configuration.
type JWTAuthApplyConfiguration struct {
	// The realm of the JWT.
	Realm *string `json:"realm,omitempty"`
	// The name of the Kubernetes secret that stores the Htpasswd configuration. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/htpasswd, and the config must be stored in the secret under the key htpasswd, otherwise the secret will be rejected as invalid.
	Secret *string `json:"secret,omitempty"`
	// The token specifies a variable that contains the JSON Web Token. By default the JWT is passed in the Authorization header as a Bearer Token. JWT may be also passed as a cookie or a part of a query string, for example: $cookie_auth_token. Accepted variables are $http_, $arg_, $cookie_.
	Token *string `json:"token,omitempty"`
	// The remote URI where the request will be sent to retrieve JSON Web Key set
	JwksURI *string `json:"jwksURI,omitempty"`
	// Enables in-memory caching of JWKS (JSON Web Key Sets) that are obtained from the jwksURI and sets a valid time for expiration.
	KeyCache *string `json:"keyCache,omitempty"`
	// Enables SNI (Server Name Indication) for the JWT policy. This is useful when the remote server requires SNI to serve the correct certificate.
	SNIEnabled *bool `json:"sniEnabled,omitempty"`
	// The SNI name to use when connecting to the remote server. If not set, the hostname from the “jwksURI“ will be used.
	SNIName *string `json:"sniName,omitempty"`
	// Enables verification of the JWKS server SSL certificate. Default is false.
	SSLVerify *bool `json:"sslVerify,omitempty"`
	// The name of the Kubernetes secret that stores the CA certificate for JWKS server verification. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/ca, and the certificate must be stored in the secret under the key ca.crt.
	TrustedCertSecret *string `json:"trustedCertSecret,omitempty"`
	// Sets the verification depth in the JWKS server certificates chain. The default is 1.
	SSLVerifyDepth *int `json:"sslVerifyDepth,omitempty"`
}

// JWTAuthApplyConfiguration constructs a declarative configuration of the JWTAuth type for use with
// apply.
func JWTAuth() *JWTAuthApplyConfiguration {
	return &JWTAuthApplyConfiguration{}
}

// WithRealm sets the Realm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Realm field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithRealm(value string) *JWTAuthApplyConfiguration {
	b.Realm = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithSecret(value string) *JWTAuthApplyConfiguration {
	b.Secret = &value
	return b
}

// WithToken sets the Token field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Token field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithToken(value string) *JWTAuthApplyConfiguration {
	b.Token = &value
	return b
}

// WithJwksURI sets the JwksURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JwksURI field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithJwksURI(value string) *JWTAuthApplyConfiguration {
	b.JwksURI = &value
	return b
}

// WithKeyCache sets the KeyCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyCache field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithKeyCache(value string) *JWTAuthApplyConfiguration {
	b.KeyCache = &value
	return b
}

// WithSNIEnabled sets the SNIEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SNIEnabled field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithSNIEnabled(value bool) *JWTAuthApplyConfiguration {
	b.SNIEnabled = &value
	return b
}

// WithSNIName sets the SNIName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SNIName field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithSNIName(value string) *JWTAuthApplyConfiguration {
	b.SNIName = &value
	return b
}

// WithSSLVerify sets the SSLVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerify field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithSSLVerify(value bool) *JWTAuthApplyConfiguration {
	b.SSLVerify = &value
	return b
}

// WithTrustedCertSecret sets the TrustedCertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustedCertSecret field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithTrustedCertSecret(value string) *JWTAuthApplyConfiguration {
	b.TrustedCertSecret = &value
	return b
}

// WithSSLVerifyDepth sets the SSLVerifyDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerifyDepth field is set to the value of the last call.
func (b *JWTAuthApplyConfiguration) WithSSLVerifyDepth(value int) *JWTAuthApplyConfiguration {
	b.SSLVerifyDepth = &value
	return b
}
