// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// JWTConditionApplyConfiguration represents a declarative configuration of the JWTCondition type for use
// with apply.
//
// JWTCondition defines a condition for a rate limit by JWT claim.
type JWTConditionApplyConfiguration struct {
	// the JWT claim to be rate limit by. Nested claims should be separated by "."
	Claim *string `json:"claim,omitempty"`
	// the value of the claim to match against.
	Match *string `json:"match,omitempty"`
}

// JWTConditionApplyConfiguration constructs a declarative configuration of the JWTCondition type for use with
// apply.
func JWTCondition() *JWTConditionApplyConfiguration {
	return &JWTConditionApplyConfiguration{}
}

// WithClaim sets the Claim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Claim field is set to the value of the last call.
func (b *JWTConditionApplyConfiguration) WithClaim(value string) *JWTConditionApplyConfiguration {
	b.Claim = &value
	return b
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *JWTConditionApplyConfiguration) WithMatch(value string) *JWTConditionApplyConfiguration {
	b.Match = &value
	return b
}
