// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ListenerApplyConfiguration represents a declarative configuration of the Listener type for use
// with apply.
//
// Listener defines a listener.
type ListenerApplyConfiguration struct {
	// The name of the listener. The name must be unique across all listeners.
	Name *string `json:"name,omitempty"`
	// The protocol of the listener. For example, HTTP.
	Protocol *string `json:"protocol,omitempty"`
	// The port on which the listener will accept connections.
	Port *int `json:"port,omitempty"`
	// Specifies the IPv4 address to listen on.
	IPv4 *string `json:"ipv4,omitempty"`
	// ipv6 addresse that NGINX will listen on.
	IPv6 *string `json:"ipv6,omitempty"`
	// Whether the listener will be listening for SSL connections
	Ssl *bool `json:"ssl,omitempty"`
}

// ListenerApplyConfiguration constructs a declarative configuration of the Listener type for use with
// apply.
func Listener() *ListenerApplyConfiguration {
	return &ListenerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ListenerApplyConfiguration) WithName(value string) *ListenerApplyConfiguration {
	b.Name = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ListenerApplyConfiguration) WithProtocol(value string) *ListenerApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ListenerApplyConfiguration) WithPort(value int) *ListenerApplyConfiguration {
	b.Port = &value
	return b
}

// WithIPv4 sets the IPv4 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPv4 field is set to the value of the last call.
func (b *ListenerApplyConfiguration) WithIPv4(value string) *ListenerApplyConfiguration {
	b.IPv4 = &value
	return b
}

// WithIPv6 sets the IPv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPv6 field is set to the value of the last call.
func (b *ListenerApplyConfiguration) WithIPv6(value string) *ListenerApplyConfiguration {
	b.IPv6 = &value
	return b
}

// WithSsl sets the Ssl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ssl field is set to the value of the last call.
func (b *ListenerApplyConfiguration) WithSsl(value bool) *ListenerApplyConfiguration {
	b.Ssl = &value
	return b
}
