// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MatchApplyConfiguration represents a declarative configuration of the Match type for use
// with apply.
//
// Match defines a match.
type MatchApplyConfiguration struct {
	// A list of conditions. Must include at least 1 condition.
	Conditions []ConditionApplyConfiguration `json:"conditions,omitempty"`
	// The action to perform for a request.
	Action *ActionApplyConfiguration `json:"action,omitempty"`
	// The splits configuration for traffic splitting. Must include at least 2 splits.
	Splits []SplitApplyConfiguration `json:"splits,omitempty"`
}

// MatchApplyConfiguration constructs a declarative configuration of the Match type for use with
// apply.
func Match() *MatchApplyConfiguration {
	return &MatchApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MatchApplyConfiguration) WithConditions(values ...*ConditionApplyConfiguration) *MatchApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *MatchApplyConfiguration) WithAction(value *ActionApplyConfiguration) *MatchApplyConfiguration {
	b.Action = value
	return b
}

// WithSplits adds the given value to the Splits field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Splits field.
func (b *MatchApplyConfiguration) WithSplits(values ...*SplitApplyConfiguration) *MatchApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSplits")
		}
		b.Splits = append(b.Splits, *values[i])
	}
	return b
}
