// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// OIDCApplyConfiguration represents a declarative configuration of the OIDC type for use
// with apply.
//
// The OIDC policy configures NGINX Plus as a relying party for OpenID Connect authentication.
type OIDCApplyConfiguration struct {
	// URL for the authorization endpoint provided by your OpenID Connect provider.
	AuthEndpoint *string `json:"authEndpoint,omitempty"`
	// URL for the token endpoint provided by your OpenID Connect provider.
	TokenEndpoint *string `json:"tokenEndpoint,omitempty"`
	// URL for the JSON Web Key Set (JWK) document provided by your OpenID Connect provider.
	JWKSURI *string `json:"jwksURI,omitempty"`
	// The client ID provided by your OpenID Connect provider.
	ClientID *string `json:"clientID,omitempty"`
	// The name of the Kubernetes secret that stores the client secret provided by your OpenID Connect provider. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/oidc, and the secret under the key client-secret, otherwise the secret will be rejected as invalid. If PKCE is enabled, this should be not configured.
	ClientSecret *string `json:"clientSecret,omitempty"`
	// List of OpenID Connect scopes. The scope openid always needs to be present and others can be added concatenating them with a + sign, for example openid+profile+email, openid+email+userDefinedScope. The default is openid.
	Scope *string `json:"scope,omitempty"`
	// Allows overriding the default redirect URI. The default is /_codexch.
	RedirectURI *string `json:"redirectURI,omitempty"`
	// URL provided by your OpenID Connect provider to request the end user be logged out.
	EndSessionEndpoint *string `json:"endSessionEndpoint,omitempty"`
	// URI to redirect to after the logout has been performed. Requires endSessionEndpoint. The default is /_logout.
	PostLogoutRedirectURI *string `json:"postLogoutRedirectURI,omitempty"`
	// Specifies the maximum timeout in milliseconds for synchronizing ID/access tokens and shared values between Ingress Controller pods. The default is 200.
	ZoneSyncLeeway *int `json:"zoneSyncLeeway,omitempty"`
	// A list of extra URL arguments to pass to the authorization endpoint provided by your OpenID Connect provider. Arguments must be URL encoded, multiple arguments may be included in the list, for example [ arg1=value1, arg2=value2 ]
	AuthExtraArgs []string `json:"authExtraArgs,omitempty"`
	// Option of whether Bearer token is used to authorize NGINX to access protected backend.
	AccessTokenEnable *bool `json:"accessTokenEnable,omitempty"`
	// Switches Proof Key for Code Exchange on. The OpenID client needs to be in public mode. clientSecret is not used in this mode.
	PKCEEnable *bool `json:"pkceEnable,omitempty"`
	// Enables verification of the IDP server SSL certificate. Default is false.
	SSLVerify *bool `json:"sslVerify,omitempty"`
	// The name of the Kubernetes secret that stores the CA certificate for IDP server verification. It must be in the same namespace as the Policy resource. The secret must be of the type nginx.org/ca, and the certificate must be stored in the secret under the key ca.crt.
	TrustedCertSecret *string `json:"trustedCertSecret,omitempty"`
	// Sets the verification depth in the IDP server certificates chain. The default is 1.
	SSLVerifyDepth *int `json:"sslVerifyDepth,omitempty"`
}

// OIDCApplyConfiguration constructs a declarative configuration of the OIDC type for use with
// apply.
func OIDC() *OIDCApplyConfiguration {
	return &OIDCApplyConfiguration{}
}

// WithAuthEndpoint sets the AuthEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthEndpoint field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithAuthEndpoint(value string) *OIDCApplyConfiguration {
	b.AuthEndpoint = &value
	return b
}

// WithTokenEndpoint sets the TokenEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenEndpoint field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithTokenEndpoint(value string) *OIDCApplyConfiguration {
	b.TokenEndpoint = &value
	return b
}

// WithJWKSURI sets the JWKSURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWKSURI field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithJWKSURI(value string) *OIDCApplyConfiguration {
	b.JWKSURI = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithClientID(value string) *OIDCApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithClientSecret(value string) *OIDCApplyConfiguration {
	b.ClientSecret = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithScope(value string) *OIDCApplyConfiguration {
	b.Scope = &value
	return b
}

// WithRedirectURI sets the RedirectURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedirectURI field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithRedirectURI(value string) *OIDCApplyConfiguration {
	b.RedirectURI = &value
	return b
}

// WithEndSessionEndpoint sets the EndSessionEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndSessionEndpoint field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithEndSessionEndpoint(value string) *OIDCApplyConfiguration {
	b.EndSessionEndpoint = &value
	return b
}

// WithPostLogoutRedirectURI sets the PostLogoutRedirectURI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PostLogoutRedirectURI field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithPostLogoutRedirectURI(value string) *OIDCApplyConfiguration {
	b.PostLogoutRedirectURI = &value
	return b
}

// WithZoneSyncLeeway sets the ZoneSyncLeeway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneSyncLeeway field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithZoneSyncLeeway(value int) *OIDCApplyConfiguration {
	b.ZoneSyncLeeway = &value
	return b
}

// WithAuthExtraArgs adds the given value to the AuthExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthExtraArgs field.
func (b *OIDCApplyConfiguration) WithAuthExtraArgs(values ...string) *OIDCApplyConfiguration {
	for i := range values {
		b.AuthExtraArgs = append(b.AuthExtraArgs, values[i])
	}
	return b
}

// WithAccessTokenEnable sets the AccessTokenEnable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessTokenEnable field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithAccessTokenEnable(value bool) *OIDCApplyConfiguration {
	b.AccessTokenEnable = &value
	return b
}

// WithPKCEEnable sets the PKCEEnable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PKCEEnable field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithPKCEEnable(value bool) *OIDCApplyConfiguration {
	b.PKCEEnable = &value
	return b
}

// WithSSLVerify sets the SSLVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerify field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithSSLVerify(value bool) *OIDCApplyConfiguration {
	b.SSLVerify = &value
	return b
}

// WithTrustedCertSecret sets the TrustedCertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustedCertSecret field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithTrustedCertSecret(value string) *OIDCApplyConfiguration {
	b.TrustedCertSecret = &value
	return b
}

// WithSSLVerifyDepth sets the SSLVerifyDepth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerifyDepth field is set to the value of the last call.
func (b *OIDCApplyConfiguration) WithSSLVerifyDepth(value int) *OIDCApplyConfiguration {
	b.SSLVerifyDepth = &value
	return b
}
