// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PolicyStatusApplyConfiguration represents a declarative configuration of the PolicyStatus type for use
// with apply.
//
// PolicyStatus is the status of the policy resource
type PolicyStatusApplyConfiguration struct {
	// Represents the current state of the resource. There are three possible values: Valid, Invalid and Warning. Valid indicates that the resource has been validated and accepted by the Ingress Controller. Invalid means the resource failed validation or
	State *string `json:"state,omitempty"`
	// The reason of the current state of the resource.
	Reason *string `json:"reason,omitempty"`
	// The message of the current state of the resource. It can contain more detailed information about the reason.
	Message *string `json:"message,omitempty"`
}

// PolicyStatusApplyConfiguration constructs a declarative configuration of the PolicyStatus type for use with
// apply.
func PolicyStatus() *PolicyStatusApplyConfiguration {
	return &PolicyStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithState(value string) *PolicyStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithReason(value string) *PolicyStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithMessage(value string) *PolicyStatusApplyConfiguration {
	b.Message = &value
	return b
}
