// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PolicySpecApplyConfiguration represents a declarative configuration of the PolicySpec type for use
// with apply.
//
// PolicySpec is the spec of the Policy resource.
// The spec includes multiple fields, where each field represents a different policy.
// Only one policy (field) is allowed.
type PolicySpecApplyConfiguration struct {
	// Specifies which instance of NGINX Ingress Controller must handle the Policy resource.
	IngressClass *string `json:"ingressClassName,omitempty"`
	// The access control policy based on the client IP address.
	AccessControl *AccessControlApplyConfiguration `json:"accessControl,omitempty"`
	// The rate limit policy controls the rate of processing requests per a defined key.
	RateLimit *RateLimitApplyConfiguration `json:"rateLimit,omitempty"`
	// The JWT policy configures NGINX Plus to authenticate client requests using JSON Web Tokens.
	JWTAuth *JWTAuthApplyConfiguration `json:"jwt,omitempty"`
	// The basic auth policy configures NGINX to authenticate client requests using HTTP Basic authentication credentials.
	BasicAuth *BasicAuthApplyConfiguration `json:"basicAuth,omitempty"`
	// The IngressMTLS policy configures client certificate verification.
	IngressMTLS *IngressMTLSApplyConfiguration `json:"ingressMTLS,omitempty"`
	// The EgressMTLS policy configures upstreams authentication and certificate verification.
	EgressMTLS *EgressMTLSApplyConfiguration `json:"egressMTLS,omitempty"`
	// The OpenID Connect policy configures NGINX to authenticate client requests by validating a JWT token against an OAuth2/OIDC token provider, such as Auth0 or Keycloak.
	OIDC *OIDCApplyConfiguration `json:"oidc,omitempty"`
	// The WAF policy configures WAF and log configuration policies for NGINX AppProtect
	WAF *WAFApplyConfiguration `json:"waf,omitempty"`
	// The API Key policy configures NGINX to authorize requests which provide a valid API Key in a specified header or query param.
	APIKey *APIKeyApplyConfiguration `json:"apiKey,omitempty"`
	// The Cache Key defines a cache policy for proxy caching
	Cache *CacheApplyConfiguration `json:"cache,omitempty"`
}

// PolicySpecApplyConfiguration constructs a declarative configuration of the PolicySpec type for use with
// apply.
func PolicySpec() *PolicySpecApplyConfiguration {
	return &PolicySpecApplyConfiguration{}
}

// WithIngressClass sets the IngressClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClass field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithIngressClass(value string) *PolicySpecApplyConfiguration {
	b.IngressClass = &value
	return b
}

// WithAccessControl sets the AccessControl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessControl field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithAccessControl(value *AccessControlApplyConfiguration) *PolicySpecApplyConfiguration {
	b.AccessControl = value
	return b
}

// WithRateLimit sets the RateLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimit field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithRateLimit(value *RateLimitApplyConfiguration) *PolicySpecApplyConfiguration {
	b.RateLimit = value
	return b
}

// WithJWTAuth sets the JWTAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWTAuth field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithJWTAuth(value *JWTAuthApplyConfiguration) *PolicySpecApplyConfiguration {
	b.JWTAuth = value
	return b
}

// WithBasicAuth sets the BasicAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasicAuth field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithBasicAuth(value *BasicAuthApplyConfiguration) *PolicySpecApplyConfiguration {
	b.BasicAuth = value
	return b
}

// WithIngressMTLS sets the IngressMTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressMTLS field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithIngressMTLS(value *IngressMTLSApplyConfiguration) *PolicySpecApplyConfiguration {
	b.IngressMTLS = value
	return b
}

// WithEgressMTLS sets the EgressMTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EgressMTLS field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithEgressMTLS(value *EgressMTLSApplyConfiguration) *PolicySpecApplyConfiguration {
	b.EgressMTLS = value
	return b
}

// WithOIDC sets the OIDC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OIDC field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithOIDC(value *OIDCApplyConfiguration) *PolicySpecApplyConfiguration {
	b.OIDC = value
	return b
}

// WithWAF sets the WAF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WAF field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithWAF(value *WAFApplyConfiguration) *PolicySpecApplyConfiguration {
	b.WAF = value
	return b
}

// WithAPIKey sets the APIKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIKey field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithAPIKey(value *APIKeyApplyConfiguration) *PolicySpecApplyConfiguration {
	b.APIKey = value
	return b
}

// WithCache sets the Cache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cache field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithCache(value *CacheApplyConfiguration) *PolicySpecApplyConfiguration {
	b.Cache = value
	return b
}
