// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PolicyReferenceApplyConfiguration represents a declarative configuration of the PolicyReference type for use
// with apply.
//
// PolicyReference references a policy by name and an optional namespace.
type PolicyReferenceApplyConfiguration struct {
	// The name of a policy. If the policy doesn’t exist or invalid, NGINX will respond with an error response with the 500 status code.
	Name *string `json:"name,omitempty"`
	// The namespace of a policy. If not specified, the namespace of the VirtualServer resource is used.
	Namespace *string `json:"namespace,omitempty"`
}

// PolicyReferenceApplyConfiguration constructs a declarative configuration of the PolicyReference type for use with
// apply.
func PolicyReference() *PolicyReferenceApplyConfiguration {
	return &PolicyReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PolicyReferenceApplyConfiguration) WithName(value string) *PolicyReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PolicyReferenceApplyConfiguration) WithNamespace(value string) *PolicyReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
