// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ProxyRequestHeadersApplyConfiguration represents a declarative configuration of the ProxyRequestHeaders type for use
// with apply.
//
// ProxyRequestHeaders defines the request headers manipulation in an ActionProxy.
type ProxyRequestHeadersApplyConfiguration struct {
	// Passes the original request headers to the proxied upstream server.  Default is true.
	Pass *bool `json:"pass,omitempty"`
	// Allows redefining or appending fields to present request headers passed to the proxied upstream servers.
	Set []HeaderApplyConfiguration `json:"set,omitempty"`
}

// ProxyRequestHeadersApplyConfiguration constructs a declarative configuration of the ProxyRequestHeaders type for use with
// apply.
func ProxyRequestHeaders() *ProxyRequestHeadersApplyConfiguration {
	return &ProxyRequestHeadersApplyConfiguration{}
}

// WithPass sets the Pass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pass field is set to the value of the last call.
func (b *ProxyRequestHeadersApplyConfiguration) WithPass(value bool) *ProxyRequestHeadersApplyConfiguration {
	b.Pass = &value
	return b
}

// WithSet adds the given value to the Set field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Set field.
func (b *ProxyRequestHeadersApplyConfiguration) WithSet(values ...*HeaderApplyConfiguration) *ProxyRequestHeadersApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSet")
		}
		b.Set = append(b.Set, *values[i])
	}
	return b
}
