// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ProxyResponseHeadersApplyConfiguration represents a declarative configuration of the ProxyResponseHeaders type for use
// with apply.
//
// ProxyResponseHeaders defines the response headers manipulation in an ActionProxy.
type ProxyResponseHeadersApplyConfiguration struct {
	// The headers that will not be passed* in the response to the client from a proxied upstream server.
	Hide []string `json:"hide,omitempty"`
	// Allows passing the hidden header fields* to the client from a proxied upstream server.
	Pass []string `json:"pass,omitempty"`
	// Disables processing of certain headers** to the client from a proxied upstream server.
	Ignore []string `json:"ignore,omitempty"`
	// Adds headers to the response to the client.
	Add []AddHeaderApplyConfiguration `json:"add,omitempty"`
}

// ProxyResponseHeadersApplyConfiguration constructs a declarative configuration of the ProxyResponseHeaders type for use with
// apply.
func ProxyResponseHeaders() *ProxyResponseHeadersApplyConfiguration {
	return &ProxyResponseHeadersApplyConfiguration{}
}

// WithHide adds the given value to the Hide field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Hide field.
func (b *ProxyResponseHeadersApplyConfiguration) WithHide(values ...string) *ProxyResponseHeadersApplyConfiguration {
	for i := range values {
		b.Hide = append(b.Hide, values[i])
	}
	return b
}

// WithPass adds the given value to the Pass field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pass field.
func (b *ProxyResponseHeadersApplyConfiguration) WithPass(values ...string) *ProxyResponseHeadersApplyConfiguration {
	for i := range values {
		b.Pass = append(b.Pass, values[i])
	}
	return b
}

// WithIgnore adds the given value to the Ignore field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ignore field.
func (b *ProxyResponseHeadersApplyConfiguration) WithIgnore(values ...string) *ProxyResponseHeadersApplyConfiguration {
	for i := range values {
		b.Ignore = append(b.Ignore, values[i])
	}
	return b
}

// WithAdd adds the given value to the Add field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Add field.
func (b *ProxyResponseHeadersApplyConfiguration) WithAdd(values ...*AddHeaderApplyConfiguration) *ProxyResponseHeadersApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdd")
		}
		b.Add = append(b.Add, *values[i])
	}
	return b
}
