// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// RateLimitApplyConfiguration represents a declarative configuration of the RateLimit type for use
// with apply.
//
// RateLimit defines a rate limit policy.
type RateLimitApplyConfiguration struct {
	// The rate of requests permitted. The rate is specified in requests per second (r/s) or requests per minute (r/m).
	Rate *string `json:"rate,omitempty"`
	// The key to which the rate limit is applied. Can contain text, variables, or a combination of them.
	// Variables must be surrounded by ${}. For example: ${binary_remote_addr}. Accepted variables are
	// $binary_remote_addr, $request_uri, $request_method, $url, $http_, $args, $arg_, $cookie_,$jwt_claim_ .
	Key *string `json:"key,omitempty"`
	// The delay parameter specifies a limit at which excessive requests become delayed. If not set all excessive requests are delayed.
	Delay *int `json:"delay,omitempty"`
	// Disables the delaying of excessive requests while requests are being limited. Overrides delay if both are set.
	NoDelay *bool `json:"noDelay,omitempty"`
	// Excessive requests are delayed until their number exceeds the burst size, in which case the request is terminated with an error.
	Burst *int `json:"burst,omitempty"`
	// Size of the shared memory zone. Only positive values are allowed. Allowed suffixes are k or m, if none are present k is assumed.
	ZoneSize *string `json:"zoneSize,omitempty"`
	// Enables the dry run mode. In this mode, the rate limit is not actually applied, but the number of excessive requests is accounted as usual in the shared memory zone.
	DryRun *bool `json:"dryRun,omitempty"`
	// Sets the desired logging level for cases when the server refuses to process requests due to rate exceeding, or delays request processing. Allowed values are info, notice, warn or error. Default is error.
	LogLevel *string `json:"logLevel,omitempty"`
	// Sets the status code to return in response to rejected requests. Must fall into the range 400..599. Default is 503.
	RejectCode *int `json:"rejectCode,omitempty"`
	// Enables a constant rate-limit by dividing the configured rate by the number of nginx-ingress pods currently serving traffic. This adjustment ensures that the rate-limit remains consistent, even as the number of nginx-pods fluctuates due to autoscaling. This will not work properly if requests from a client are not evenly distributed across all ingress pods (Such as with sticky sessions, long lived TCP Connections with many requests, and so forth). In such cases using zone-sync instead would give better results. Enabling zone-sync will suppress this setting.
	Scale *bool `json:"scale,omitempty"`
	// Add a condition to a rate-limit policy.
	Condition *RateLimitConditionApplyConfiguration `json:"condition,omitempty"`
}

// RateLimitApplyConfiguration constructs a declarative configuration of the RateLimit type for use with
// apply.
func RateLimit() *RateLimitApplyConfiguration {
	return &RateLimitApplyConfiguration{}
}

// WithRate sets the Rate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rate field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithRate(value string) *RateLimitApplyConfiguration {
	b.Rate = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithKey(value string) *RateLimitApplyConfiguration {
	b.Key = &value
	return b
}

// WithDelay sets the Delay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delay field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithDelay(value int) *RateLimitApplyConfiguration {
	b.Delay = &value
	return b
}

// WithNoDelay sets the NoDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NoDelay field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithNoDelay(value bool) *RateLimitApplyConfiguration {
	b.NoDelay = &value
	return b
}

// WithBurst sets the Burst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Burst field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithBurst(value int) *RateLimitApplyConfiguration {
	b.Burst = &value
	return b
}

// WithZoneSize sets the ZoneSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneSize field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithZoneSize(value string) *RateLimitApplyConfiguration {
	b.ZoneSize = &value
	return b
}

// WithDryRun sets the DryRun field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DryRun field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithDryRun(value bool) *RateLimitApplyConfiguration {
	b.DryRun = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithLogLevel(value string) *RateLimitApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithRejectCode sets the RejectCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RejectCode field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithRejectCode(value int) *RateLimitApplyConfiguration {
	b.RejectCode = &value
	return b
}

// WithScale sets the Scale field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scale field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithScale(value bool) *RateLimitApplyConfiguration {
	b.Scale = &value
	return b
}

// WithCondition sets the Condition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Condition field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithCondition(value *RateLimitConditionApplyConfiguration) *RateLimitApplyConfiguration {
	b.Condition = value
	return b
}
