// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// RateLimitConditionApplyConfiguration represents a declarative configuration of the RateLimitCondition type for use
// with apply.
//
// RateLimitCondition defines a condition for a rate limit policy.
type RateLimitConditionApplyConfiguration struct {
	// defines a JWT condition to rate limit against.
	JWT *JWTConditionApplyConfiguration `json:"jwt,omitempty"`
	// defines a Variables condition to rate limit against.
	Variables *[]VariableConditionApplyConfiguration `json:"variables,omitempty"`
	// sets the rate limit in this policy to be the default if no conditions are met. In a group of policies with the same condition, only one policy can be the default.
	Default *bool `json:"default,omitempty"`
}

// RateLimitConditionApplyConfiguration constructs a declarative configuration of the RateLimitCondition type for use with
// apply.
func RateLimitCondition() *RateLimitConditionApplyConfiguration {
	return &RateLimitConditionApplyConfiguration{}
}

// WithJWT sets the JWT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWT field is set to the value of the last call.
func (b *RateLimitConditionApplyConfiguration) WithJWT(value *JWTConditionApplyConfiguration) *RateLimitConditionApplyConfiguration {
	b.JWT = value
	return b
}

func (b *RateLimitConditionApplyConfiguration) ensureVariableConditionApplyConfigurationExists() {
	if b.Variables == nil {
		b.Variables = &[]VariableConditionApplyConfiguration{}
	}
}

// WithVariables adds the given value to the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Variables field.
func (b *RateLimitConditionApplyConfiguration) WithVariables(values ...*VariableConditionApplyConfiguration) *RateLimitConditionApplyConfiguration {
	b.ensureVariableConditionApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVariables")
		}
		*b.Variables = append(*b.Variables, *values[i])
	}
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *RateLimitConditionApplyConfiguration) WithDefault(value bool) *RateLimitConditionApplyConfiguration {
	b.Default = &value
	return b
}
