// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// RouteApplyConfiguration represents a declarative configuration of the Route type for use
// with apply.
//
// Route defines a route.
type RouteApplyConfiguration struct {
	// The path of the route. NGINX will match it against the URI of a request. Possible values are: a prefix ( / , /path ), an exact match ( =/exact/match ), a case insensitive regular expression ( ~*^/Bar.*\.jpg ) or a case sensitive regular expression ( ~^/foo.*\.jpg ). In the case of a prefix (must start with / ) or an exact match (must start with = ), the path must not include any whitespace characters, { , } or ;. In the case of the regex matches, all double quotes " must be escaped and the match can’t end in an unescaped backslash \. The path must be unique among the paths of all routes of the VirtualServer. Check the location directive for more information.
	Path *string `json:"path,omitempty"`
	// A list of policies. The policies override the policies of the same type defined in the spec of the VirtualServer.
	Policies []PolicyReferenceApplyConfiguration `json:"policies,omitempty"`
	// The name of a VirtualServerRoute resource that defines this route. If the VirtualServerRoute belongs to a different namespace than the VirtualServer, you need to include the namespace. For example, tea-namespace/tea.
	Route *string `json:"route,omitempty"`
	// The default action to perform for a request.
	Action *ActionApplyConfiguration `json:"action,omitempty"`
	// The default splits configuration for traffic splitting. Must include at least 2 splits.
	Splits []SplitApplyConfiguration `json:"splits,omitempty"`
	// The matching rules for advanced content-based routing. Requires the default Action or Splits. Unmatched requests will be handled by the default Action or Splits.
	Matches []MatchApplyConfiguration `json:"matches,omitempty"`
	// The custom responses for error codes. NGINX will use those responses instead of returning the error responses from the upstream servers or the default responses generated by NGINX. A custom response can be a redirect or a canned response. For example, a redirect to another URL if an upstream server responded with a 404 status code.
	ErrorPages []ErrorPageApplyConfiguration `json:"errorPages,omitempty"`
	// Sets a custom snippet in the location context. Overrides the location-snippets ConfigMap key.
	LocationSnippets *string `json:"location-snippets,omitempty"`
	// A reference to a DosProtectedResource, setting this enables DOS protection of the VirtualServer route.
	Dos *string `json:"dos,omitempty"`
}

// RouteApplyConfiguration constructs a declarative configuration of the Route type for use with
// apply.
func Route() *RouteApplyConfiguration {
	return &RouteApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithPath(value string) *RouteApplyConfiguration {
	b.Path = &value
	return b
}

// WithPolicies adds the given value to the Policies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Policies field.
func (b *RouteApplyConfiguration) WithPolicies(values ...*PolicyReferenceApplyConfiguration) *RouteApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPolicies")
		}
		b.Policies = append(b.Policies, *values[i])
	}
	return b
}

// WithRoute sets the Route field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Route field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithRoute(value string) *RouteApplyConfiguration {
	b.Route = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithAction(value *ActionApplyConfiguration) *RouteApplyConfiguration {
	b.Action = value
	return b
}

// WithSplits adds the given value to the Splits field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Splits field.
func (b *RouteApplyConfiguration) WithSplits(values ...*SplitApplyConfiguration) *RouteApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSplits")
		}
		b.Splits = append(b.Splits, *values[i])
	}
	return b
}

// WithMatches adds the given value to the Matches field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Matches field.
func (b *RouteApplyConfiguration) WithMatches(values ...*MatchApplyConfiguration) *RouteApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatches")
		}
		b.Matches = append(b.Matches, *values[i])
	}
	return b
}

// WithErrorPages adds the given value to the ErrorPages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ErrorPages field.
func (b *RouteApplyConfiguration) WithErrorPages(values ...*ErrorPageApplyConfiguration) *RouteApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithErrorPages")
		}
		b.ErrorPages = append(b.ErrorPages, *values[i])
	}
	return b
}

// WithLocationSnippets sets the LocationSnippets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocationSnippets field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithLocationSnippets(value string) *RouteApplyConfiguration {
	b.LocationSnippets = &value
	return b
}

// WithDos sets the Dos field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dos field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithDos(value string) *RouteApplyConfiguration {
	b.Dos = &value
	return b
}
