// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SecurityLogApplyConfiguration represents a declarative configuration of the SecurityLog type for use
// with apply.
//
// SecurityLog defines the security log of a WAF policy.
type SecurityLogApplyConfiguration struct {
	// Enables security log.
	Enable *bool `json:"enable,omitempty"`
	// The App Protect WAF log conf resource. Accepts an optional namespace. Only works with apPolicy.
	ApLogConf *string `json:"apLogConf,omitempty"`
	// The App Protect WAF log bundle resource. Only works with apBundle.
	ApLogBundle *string `json:"apLogBundle,omitempty"`
	// The log destination for the security log. Only accepted variables are syslog:server=<ip-address>; localhost; fqdn>:<port>, stderr, <absolute path to file>.
	LogDest *string `json:"logDest,omitempty"`
}

// SecurityLogApplyConfiguration constructs a declarative configuration of the SecurityLog type for use with
// apply.
func SecurityLog() *SecurityLogApplyConfiguration {
	return &SecurityLogApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *SecurityLogApplyConfiguration) WithEnable(value bool) *SecurityLogApplyConfiguration {
	b.Enable = &value
	return b
}

// WithApLogConf sets the ApLogConf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApLogConf field is set to the value of the last call.
func (b *SecurityLogApplyConfiguration) WithApLogConf(value string) *SecurityLogApplyConfiguration {
	b.ApLogConf = &value
	return b
}

// WithApLogBundle sets the ApLogBundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApLogBundle field is set to the value of the last call.
func (b *SecurityLogApplyConfiguration) WithApLogBundle(value string) *SecurityLogApplyConfiguration {
	b.ApLogBundle = &value
	return b
}

// WithLogDest sets the LogDest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogDest field is set to the value of the last call.
func (b *SecurityLogApplyConfiguration) WithLogDest(value string) *SecurityLogApplyConfiguration {
	b.LogDest = &value
	return b
}
