// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SessionCookieApplyConfiguration represents a declarative configuration of the SessionCookie type for use
// with apply.
//
// SessionCookie defines the parameters for session persistence.
type SessionCookieApplyConfiguration struct {
	// Enables session persistence with a session cookie for an upstream server. The default is false.
	Enable *bool `json:"enable,omitempty"`
	// The name of the cookie.
	Name *string `json:"name,omitempty"`
	// The path for which the cookie is set.
	Path *string `json:"path,omitempty"`
	// The time for which a browser should keep the cookie. Can be set to the special value max, which will cause the cookie to expire on 31 Dec 2037 23:55:55 GMT.
	Expires *string `json:"expires,omitempty"`
	// The domain for which the cookie is set.
	Domain *string `json:"domain,omitempty"`
	// Adds the HttpOnly attribute to the cookie.
	HTTPOnly *bool `json:"httpOnly,omitempty"`
	// Adds the Secure attribute to the cookie.
	Secure *bool `json:"secure,omitempty"`
	// Adds the SameSite attribute to the cookie. The allowed values are: strict, lax, none
	SameSite *string `json:"samesite,omitempty"`
}

// SessionCookieApplyConfiguration constructs a declarative configuration of the SessionCookie type for use with
// apply.
func SessionCookie() *SessionCookieApplyConfiguration {
	return &SessionCookieApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithEnable(value bool) *SessionCookieApplyConfiguration {
	b.Enable = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithName(value string) *SessionCookieApplyConfiguration {
	b.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithPath(value string) *SessionCookieApplyConfiguration {
	b.Path = &value
	return b
}

// WithExpires sets the Expires field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expires field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithExpires(value string) *SessionCookieApplyConfiguration {
	b.Expires = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithDomain(value string) *SessionCookieApplyConfiguration {
	b.Domain = &value
	return b
}

// WithHTTPOnly sets the HTTPOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPOnly field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithHTTPOnly(value bool) *SessionCookieApplyConfiguration {
	b.HTTPOnly = &value
	return b
}

// WithSecure sets the Secure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secure field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithSecure(value bool) *SessionCookieApplyConfiguration {
	b.Secure = &value
	return b
}

// WithSameSite sets the SameSite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SameSite field is set to the value of the last call.
func (b *SessionCookieApplyConfiguration) WithSameSite(value string) *SessionCookieApplyConfiguration {
	b.SameSite = &value
	return b
}
