// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SessionParametersApplyConfiguration represents a declarative configuration of the SessionParameters type for use
// with apply.
//
// SessionParameters defines session parameters.
type SessionParametersApplyConfiguration struct {
	// The timeout between two successive read or write operations on client or proxied server connections. The default is 10m.
	Timeout *string `json:"timeout,omitempty"`
}

// SessionParametersApplyConfiguration constructs a declarative configuration of the SessionParameters type for use with
// apply.
func SessionParameters() *SessionParametersApplyConfiguration {
	return &SessionParametersApplyConfiguration{}
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *SessionParametersApplyConfiguration) WithTimeout(value string) *SessionParametersApplyConfiguration {
	b.Timeout = &value
	return b
}
