// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SplitApplyConfiguration represents a declarative configuration of the Split type for use
// with apply.
//
// Split defines a split.
type SplitApplyConfiguration struct {
	// The weight of an action. Must fall into the range 0..100. The sum of the weights of all splits must be equal to 100.
	Weight *int `json:"weight,omitempty"`
	// The action to perform for a request.
	Action *ActionApplyConfiguration `json:"action,omitempty"`
}

// SplitApplyConfiguration constructs a declarative configuration of the Split type for use with
// apply.
func Split() *SplitApplyConfiguration {
	return &SplitApplyConfiguration{}
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *SplitApplyConfiguration) WithWeight(value int) *SplitApplyConfiguration {
	b.Weight = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *SplitApplyConfiguration) WithAction(value *ActionApplyConfiguration) *SplitApplyConfiguration {
	b.Action = value
	return b
}
