// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// SuppliedInApplyConfiguration represents a declarative configuration of the SuppliedIn type for use
// with apply.
//
// SuppliedIn defines the locations API Key should be supplied in.
type SuppliedInApplyConfiguration struct {
	// The location of the API Key as a request header. For example, $http_auth. Accepted variables are $http_.
	Header []string `json:"header,omitempty"`
	// The location of the API Key as a query param. For example, $arg_apikey. Accepted variables are $arg_.
	Query []string `json:"query,omitempty"`
}

// SuppliedInApplyConfiguration constructs a declarative configuration of the SuppliedIn type for use with
// apply.
func SuppliedIn() *SuppliedInApplyConfiguration {
	return &SuppliedInApplyConfiguration{}
}

// WithHeader adds the given value to the Header field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Header field.
func (b *SuppliedInApplyConfiguration) WithHeader(values ...string) *SuppliedInApplyConfiguration {
	for i := range values {
		b.Header = append(b.Header, values[i])
	}
	return b
}

// WithQuery adds the given value to the Query field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Query field.
func (b *SuppliedInApplyConfiguration) WithQuery(values ...string) *SuppliedInApplyConfiguration {
	for i := range values {
		b.Query = append(b.Query, values[i])
	}
	return b
}
