// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TLSApplyConfiguration represents a declarative configuration of the TLS type for use
// with apply.
//
// TLS defines TLS configuration for a VirtualServer.
type TLSApplyConfiguration struct {
	// The name of a secret with a TLS certificate and key. The secret must belong to the same namespace as the VirtualServer. The secret must be of the type kubernetes.io/tls and contain keys named tls.crt and tls.key that contain the certificate and private key as described here. If the secret doesn’t exist or is invalid, NGINX will break any attempt to establish a TLS connection to the host of the VirtualServer. If the secret is not specified but wildcard TLS secret is configured, NGINX will use the wildcard secret for TLS termination.
	Secret *string `json:"secret,omitempty"`
	// The redirect configuration of the TLS for a VirtualServer.
	Redirect *TLSRedirectApplyConfiguration `json:"redirect,omitempty"`
	// The cert-manager configuration of the TLS for a VirtualServer.
	CertManager *CertManagerApplyConfiguration `json:"cert-manager,omitempty"`
}

// TLSApplyConfiguration constructs a declarative configuration of the TLS type for use with
// apply.
func TLS() *TLSApplyConfiguration {
	return &TLSApplyConfiguration{}
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *TLSApplyConfiguration) WithSecret(value string) *TLSApplyConfiguration {
	b.Secret = &value
	return b
}

// WithRedirect sets the Redirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redirect field is set to the value of the last call.
func (b *TLSApplyConfiguration) WithRedirect(value *TLSRedirectApplyConfiguration) *TLSApplyConfiguration {
	b.Redirect = value
	return b
}

// WithCertManager sets the CertManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertManager field is set to the value of the last call.
func (b *TLSApplyConfiguration) WithCertManager(value *CertManagerApplyConfiguration) *TLSApplyConfiguration {
	b.CertManager = value
	return b
}
