// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TLSRedirectApplyConfiguration represents a declarative configuration of the TLSRedirect type for use
// with apply.
//
// TLSRedirect defines a redirect for a TLS.
type TLSRedirectApplyConfiguration struct {
	// Enables a TLS redirect for a VirtualServer. The default is False.
	Enable *bool `json:"enable,omitempty"`
	// The status code of a redirect. The allowed values are: 301, 302, 307 or 308. The default is 301.
	Code *int `json:"code,omitempty"`
	// The attribute of a request that NGINX will evaluate to send a redirect. The allowed values are scheme (the scheme of the request) or x-forwarded-proto (the X-Forwarded-Proto header of the request). The default is scheme.
	BasedOn *string `json:"basedOn,omitempty"`
}

// TLSRedirectApplyConfiguration constructs a declarative configuration of the TLSRedirect type for use with
// apply.
func TLSRedirect() *TLSRedirectApplyConfiguration {
	return &TLSRedirectApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *TLSRedirectApplyConfiguration) WithEnable(value bool) *TLSRedirectApplyConfiguration {
	b.Enable = &value
	return b
}

// WithCode sets the Code field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Code field is set to the value of the last call.
func (b *TLSRedirectApplyConfiguration) WithCode(value int) *TLSRedirectApplyConfiguration {
	b.Code = &value
	return b
}

// WithBasedOn sets the BasedOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasedOn field is set to the value of the last call.
func (b *TLSRedirectApplyConfiguration) WithBasedOn(value string) *TLSRedirectApplyConfiguration {
	b.BasedOn = &value
	return b
}
