// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerActionApplyConfiguration represents a declarative configuration of the TransportServerAction type for use
// with apply.
//
// TransportServerAction defines an action.
type TransportServerActionApplyConfiguration struct {
	// Passes connections/datagrams to an upstream. The upstream with that name must be defined in the resource.
	Pass *string `json:"pass,omitempty"`
}

// TransportServerActionApplyConfiguration constructs a declarative configuration of the TransportServerAction type for use with
// apply.
func TransportServerAction() *TransportServerActionApplyConfiguration {
	return &TransportServerActionApplyConfiguration{}
}

// WithPass sets the Pass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pass field is set to the value of the last call.
func (b *TransportServerActionApplyConfiguration) WithPass(value string) *TransportServerActionApplyConfiguration {
	b.Pass = &value
	return b
}
