// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerStatusApplyConfiguration represents a declarative configuration of the TransportServerStatus type for use
// with apply.
//
// TransportServerStatus defines the status for the TransportServer resource.
type TransportServerStatusApplyConfiguration struct {
	// Represents the current state of the resource. Possible values: Valid (resource validated and accepted), Invalid (validation failed or config reload failed), or Warning (validated but may work in degraded state).
	State *string `json:"state,omitempty"`
	// The reason of the current state of the resource.
	Reason *string `json:"reason,omitempty"`
	// The message of the current state of the resource. It can contain more detailed information about the reason.
	Message *string `json:"message,omitempty"`
}

// TransportServerStatusApplyConfiguration constructs a declarative configuration of the TransportServerStatus type for use with
// apply.
func TransportServerStatus() *TransportServerStatusApplyConfiguration {
	return &TransportServerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *TransportServerStatusApplyConfiguration) WithState(value string) *TransportServerStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *TransportServerStatusApplyConfiguration) WithReason(value string) *TransportServerStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *TransportServerStatusApplyConfiguration) WithMessage(value string) *TransportServerStatusApplyConfiguration {
	b.Message = &value
	return b
}
