// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerMatchApplyConfiguration represents a declarative configuration of the TransportServerMatch type for use
// with apply.
//
// TransportServerMatch defines the parameters of a custom health check.
type TransportServerMatchApplyConfiguration struct {
	// A string to send to an upstream server.
	Send *string `json:"send,omitempty"`
	// A literal string or a regular expression that the data obtained from the server should match. The regular expression is specified with the preceding ~* modifier (for case-insensitive matching), or the ~ modifier (for case-sensitive matching). NGINX Ingress Controller validates a regular expression using the RE2 syntax.
	Expect *string `json:"expect,omitempty"`
}

// TransportServerMatchApplyConfiguration constructs a declarative configuration of the TransportServerMatch type for use with
// apply.
func TransportServerMatch() *TransportServerMatchApplyConfiguration {
	return &TransportServerMatchApplyConfiguration{}
}

// WithSend sets the Send field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Send field is set to the value of the last call.
func (b *TransportServerMatchApplyConfiguration) WithSend(value string) *TransportServerMatchApplyConfiguration {
	b.Send = &value
	return b
}

// WithExpect sets the Expect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expect field is set to the value of the last call.
func (b *TransportServerMatchApplyConfiguration) WithExpect(value string) *TransportServerMatchApplyConfiguration {
	b.Expect = &value
	return b
}
