// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerUpstreamApplyConfiguration represents a declarative configuration of the TransportServerUpstream type for use
// with apply.
//
// TransportServerUpstream defines an upstream.
type TransportServerUpstreamApplyConfiguration struct {
	// The name of the upstream. Must be a valid DNS label as defined in RFC 1035. For example, hello and upstream-123 are valid. The name must be unique among all upstreams of the resource.
	Name *string `json:"name,omitempty"`
	// The name of a service. The service must belong to the same namespace as the resource. If the service doesn’t exist, NGINX will assume the service has zero endpoints and close client connections/ignore datagrams.
	Service *string `json:"service,omitempty"`
	// The port of the service. If the service doesn’t define that port, NGINX will assume the service has zero endpoints and close client connections/ignore datagrams. The port must fall into the range 1..65535.
	Port *int `json:"port,omitempty"`
	// Sets the number of unsuccessful attempts to communicate with the server that should happen in the duration set by the failTimeout parameter to consider the server unavailable. The default is 1.
	FailTimeout *string `json:"failTimeout,omitempty"`
	// Sets the number of maximum connections to the proxied server. Default value is zero, meaning there is no limit. The default is 0.
	MaxFails *int `json:"maxFails,omitempty"`
	// Sets the time during which the specified number of unsuccessful attempts to communicate with the server should happen to consider the server unavailable and the period of time the server will be considered unavailable. The default is 10s.
	MaxConns *int `json:"maxConns,omitempty"`
	// The health check configuration for the Upstream. Note: this feature is supported only in NGINX Plus.
	HealthCheck *TransportServerHealthCheckApplyConfiguration `json:"healthCheck,omitempty"`
	// The method used to load balance the upstream servers. By default, connections are distributed between the servers using a weighted round-robin balancing method.
	LoadBalancingMethod *string `json:"loadBalancingMethod,omitempty"`
	// The name of the backup service of type ExternalName. This will be used when the primary servers are unavailable. Note: The parameter cannot be used along with the random, hash or ip_hash load balancing methods.
	Backup *string `json:"backup,omitempty"`
	// The port of the backup service. The backup port is required if the backup service name is provided. The port must fall into the range 1..65535.
	BackupPort *uint16 `json:"backupPort,omitempty"`
}

// TransportServerUpstreamApplyConfiguration constructs a declarative configuration of the TransportServerUpstream type for use with
// apply.
func TransportServerUpstream() *TransportServerUpstreamApplyConfiguration {
	return &TransportServerUpstreamApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithName(value string) *TransportServerUpstreamApplyConfiguration {
	b.Name = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithService(value string) *TransportServerUpstreamApplyConfiguration {
	b.Service = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithPort(value int) *TransportServerUpstreamApplyConfiguration {
	b.Port = &value
	return b
}

// WithFailTimeout sets the FailTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailTimeout field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithFailTimeout(value string) *TransportServerUpstreamApplyConfiguration {
	b.FailTimeout = &value
	return b
}

// WithMaxFails sets the MaxFails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxFails field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithMaxFails(value int) *TransportServerUpstreamApplyConfiguration {
	b.MaxFails = &value
	return b
}

// WithMaxConns sets the MaxConns field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConns field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithMaxConns(value int) *TransportServerUpstreamApplyConfiguration {
	b.MaxConns = &value
	return b
}

// WithHealthCheck sets the HealthCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthCheck field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithHealthCheck(value *TransportServerHealthCheckApplyConfiguration) *TransportServerUpstreamApplyConfiguration {
	b.HealthCheck = value
	return b
}

// WithLoadBalancingMethod sets the LoadBalancingMethod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancingMethod field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithLoadBalancingMethod(value string) *TransportServerUpstreamApplyConfiguration {
	b.LoadBalancingMethod = &value
	return b
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithBackup(value string) *TransportServerUpstreamApplyConfiguration {
	b.Backup = &value
	return b
}

// WithBackupPort sets the BackupPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupPort field is set to the value of the last call.
func (b *TransportServerUpstreamApplyConfiguration) WithBackupPort(value uint16) *TransportServerUpstreamApplyConfiguration {
	b.BackupPort = &value
	return b
}
