// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerSpecApplyConfiguration represents a declarative configuration of the TransportServerSpec type for use
// with apply.
//
// TransportServerSpec is the spec of the TransportServer resource.
type TransportServerSpecApplyConfiguration struct {
	// Specifies which Ingress Controller must handle the VirtualServer resource.
	IngressClass *string `json:"ingressClassName,omitempty"`
	// The TLS termination configuration.
	TLS *TransportServerTLSApplyConfiguration `json:"tls,omitempty"`
	// Sets a custom HTTP and/or HTTPS listener. Valid fields are listener.http and listener.https. Each field must reference the name of a valid listener defined in a GlobalConfiguration resource
	Listener *TransportServerListenerApplyConfiguration `json:"listener,omitempty"`
	// Sets a custom snippet in server context. Overrides the server-snippets ConfigMap key.
	ServerSnippets *string `json:"serverSnippets,omitempty"`
	// Sets a custom snippet in the stream context. Overrides the stream-snippets ConfigMap key.
	StreamSnippets *string `json:"streamSnippets,omitempty"`
	// The host (domain name) of the server. Must be a valid subdomain as defined in RFC 1123, such as my-app or hello.example.com. When using a wildcard domain like *.example.com the domain must be contained in double quotes. The host value needs to be unique among all Ingress and VirtualServer resources.
	Host *string `json:"host,omitempty"`
	// A list of upstreams.
	Upstreams []TransportServerUpstreamApplyConfiguration `json:"upstreams,omitempty"`
	// UpstreamParameters defines parameters for an upstream.
	UpstreamParameters *UpstreamParametersApplyConfiguration `json:"upstreamParameters,omitempty"`
	// The parameters of the session to be used for the Server context
	SessionParameters *SessionParametersApplyConfiguration `json:"sessionParameters,omitempty"`
	// The action to perform for a request.
	Action *TransportServerActionApplyConfiguration `json:"action,omitempty"`
}

// TransportServerSpecApplyConfiguration constructs a declarative configuration of the TransportServerSpec type for use with
// apply.
func TransportServerSpec() *TransportServerSpecApplyConfiguration {
	return &TransportServerSpecApplyConfiguration{}
}

// WithIngressClass sets the IngressClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClass field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithIngressClass(value string) *TransportServerSpecApplyConfiguration {
	b.IngressClass = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithTLS(value *TransportServerTLSApplyConfiguration) *TransportServerSpecApplyConfiguration {
	b.TLS = value
	return b
}

// WithListener sets the Listener field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listener field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithListener(value *TransportServerListenerApplyConfiguration) *TransportServerSpecApplyConfiguration {
	b.Listener = value
	return b
}

// WithServerSnippets sets the ServerSnippets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerSnippets field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithServerSnippets(value string) *TransportServerSpecApplyConfiguration {
	b.ServerSnippets = &value
	return b
}

// WithStreamSnippets sets the StreamSnippets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StreamSnippets field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithStreamSnippets(value string) *TransportServerSpecApplyConfiguration {
	b.StreamSnippets = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithHost(value string) *TransportServerSpecApplyConfiguration {
	b.Host = &value
	return b
}

// WithUpstreams adds the given value to the Upstreams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Upstreams field.
func (b *TransportServerSpecApplyConfiguration) WithUpstreams(values ...*TransportServerUpstreamApplyConfiguration) *TransportServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUpstreams")
		}
		b.Upstreams = append(b.Upstreams, *values[i])
	}
	return b
}

// WithUpstreamParameters sets the UpstreamParameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpstreamParameters field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithUpstreamParameters(value *UpstreamParametersApplyConfiguration) *TransportServerSpecApplyConfiguration {
	b.UpstreamParameters = value
	return b
}

// WithSessionParameters sets the SessionParameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionParameters field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithSessionParameters(value *SessionParametersApplyConfiguration) *TransportServerSpecApplyConfiguration {
	b.SessionParameters = value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *TransportServerSpecApplyConfiguration) WithAction(value *TransportServerActionApplyConfiguration) *TransportServerSpecApplyConfiguration {
	b.Action = value
	return b
}
