// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerListenerApplyConfiguration represents a declarative configuration of the TransportServerListener type for use
// with apply.
//
// TransportServerListener defines a listener for a TransportServer.
type TransportServerListenerApplyConfiguration struct {
	// The name of a listener defined in a GlobalConfiguration resource.
	Name *string `json:"name,omitempty"`
	// The protocol of the listener.
	Protocol *string `json:"protocol,omitempty"`
}

// TransportServerListenerApplyConfiguration constructs a declarative configuration of the TransportServerListener type for use with
// apply.
func TransportServerListener() *TransportServerListenerApplyConfiguration {
	return &TransportServerListenerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TransportServerListenerApplyConfiguration) WithName(value string) *TransportServerListenerApplyConfiguration {
	b.Name = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *TransportServerListenerApplyConfiguration) WithProtocol(value string) *TransportServerListenerApplyConfiguration {
	b.Protocol = &value
	return b
}
