// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TransportServerHealthCheckApplyConfiguration represents a declarative configuration of the TransportServerHealthCheck type for use
// with apply.
//
// TransportServerHealthCheck defines the parameters for active Upstream HealthChecks.
type TransportServerHealthCheckApplyConfiguration struct {
	// Enables a health check for an upstream server. The default is false.
	Enabled *bool `json:"enable,omitempty"`
	// This overrides the timeout set by proxy_timeout which is set in SessionParameters for health checks. The default value is 5s.
	Timeout *string `json:"timeout,omitempty"`
	// The time within which each health check will be randomly delayed. By default, there is no delay.
	Jitter *string `json:"jitter,omitempty"`
	// The port used for health check requests. By default, the server port is used. Note: in contrast with the port of the upstream, this port is not a service port, but a port of a pod.
	Port *int `json:"port,omitempty"`
	// The interval between two consecutive health checks. The default is 5s.
	Interval *string `json:"interval,omitempty"`
	// The number of consecutive passed health checks of a particular upstream server after which the server will be considered healthy. The default is 1.
	Passes *int `json:"passes,omitempty"`
	// The number of consecutive failed health checks of a particular upstream server after which this server will be considered unhealthy. The default is 1.
	Fails *int `json:"fails,omitempty"`
	// Controls the data to send and the response to expect for the healthcheck.
	Match *TransportServerMatchApplyConfiguration `json:"match,omitempty"`
}

// TransportServerHealthCheckApplyConfiguration constructs a declarative configuration of the TransportServerHealthCheck type for use with
// apply.
func TransportServerHealthCheck() *TransportServerHealthCheckApplyConfiguration {
	return &TransportServerHealthCheckApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithEnabled(value bool) *TransportServerHealthCheckApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithTimeout(value string) *TransportServerHealthCheckApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithJitter sets the Jitter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Jitter field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithJitter(value string) *TransportServerHealthCheckApplyConfiguration {
	b.Jitter = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithPort(value int) *TransportServerHealthCheckApplyConfiguration {
	b.Port = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithInterval(value string) *TransportServerHealthCheckApplyConfiguration {
	b.Interval = &value
	return b
}

// WithPasses sets the Passes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Passes field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithPasses(value int) *TransportServerHealthCheckApplyConfiguration {
	b.Passes = &value
	return b
}

// WithFails sets the Fails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fails field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithFails(value int) *TransportServerHealthCheckApplyConfiguration {
	b.Fails = &value
	return b
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *TransportServerHealthCheckApplyConfiguration) WithMatch(value *TransportServerMatchApplyConfiguration) *TransportServerHealthCheckApplyConfiguration {
	b.Match = value
	return b
}
