// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// UpstreamBuffersApplyConfiguration represents a declarative configuration of the UpstreamBuffers type for use
// with apply.
//
// UpstreamBuffers defines Buffer Configuration for an Upstream.
type UpstreamBuffersApplyConfiguration struct {
	// Configures the number of buffers. The default is set in the proxy-buffers ConfigMap key.
	Number *int `json:"number,omitempty"`
	// Configures the size of a buffer. The default is set in the proxy-buffers ConfigMap key.
	Size *string `json:"size,omitempty"`
}

// UpstreamBuffersApplyConfiguration constructs a declarative configuration of the UpstreamBuffers type for use with
// apply.
func UpstreamBuffers() *UpstreamBuffersApplyConfiguration {
	return &UpstreamBuffersApplyConfiguration{}
}

// WithNumber sets the Number field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Number field is set to the value of the last call.
func (b *UpstreamBuffersApplyConfiguration) WithNumber(value int) *UpstreamBuffersApplyConfiguration {
	b.Number = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *UpstreamBuffersApplyConfiguration) WithSize(value string) *UpstreamBuffersApplyConfiguration {
	b.Size = &value
	return b
}
