// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// UpstreamTLSApplyConfiguration represents a declarative configuration of the UpstreamTLS type for use
// with apply.
//
// UpstreamTLS defines a TLS configuration for an Upstream.
type UpstreamTLSApplyConfiguration struct {
	// Enables HTTPS for requests to upstream servers. The default is False , meaning that HTTP will be used. Note: by default, NGINX will not verify the upstream server certificate. To enable the verification, configure an EgressMTLS Policy.
	Enable *bool `json:"enable,omitempty"`
}

// UpstreamTLSApplyConfiguration constructs a declarative configuration of the UpstreamTLS type for use with
// apply.
func UpstreamTLS() *UpstreamTLSApplyConfiguration {
	return &UpstreamTLSApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *UpstreamTLSApplyConfiguration) WithEnable(value bool) *UpstreamTLSApplyConfiguration {
	b.Enable = &value
	return b
}
