// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// UpstreamParametersApplyConfiguration represents a declarative configuration of the UpstreamParameters type for use
// with apply.
//
// UpstreamParameters defines parameters for an upstream.
type UpstreamParametersApplyConfiguration struct {
	// The number of datagrams, after receiving which, the next datagram from the same client starts a new session. The default is 0.
	UDPRequests *int `json:"udpRequests,omitempty"`
	// The number of datagrams expected from the proxied server in response to a client datagram.  By default, the number of datagrams is not limited.
	UDPResponses *int `json:"udpResponses,omitempty"`
	// The timeout for establishing a connection with a proxied server.  The default is 60s.
	ConnectTimeout *string `json:"connectTimeout,omitempty"`
	// If a connection to the proxied server cannot be established, determines whether a client connection will be passed to the next server. The default is true.
	NextUpstream *bool `json:"nextUpstream,omitempty"`
	// The time allowed to pass a connection to the next server. The default is 0.
	NextUpstreamTimeout *string `json:"nextUpstreamTimeout,omitempty"`
	// The number of tries for passing a connection to the next server. The default is 0.
	NextUpstreamTries *int `json:"nextUpstreamTries,omitempty"`
}

// UpstreamParametersApplyConfiguration constructs a declarative configuration of the UpstreamParameters type for use with
// apply.
func UpstreamParameters() *UpstreamParametersApplyConfiguration {
	return &UpstreamParametersApplyConfiguration{}
}

// WithUDPRequests sets the UDPRequests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UDPRequests field is set to the value of the last call.
func (b *UpstreamParametersApplyConfiguration) WithUDPRequests(value int) *UpstreamParametersApplyConfiguration {
	b.UDPRequests = &value
	return b
}

// WithUDPResponses sets the UDPResponses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UDPResponses field is set to the value of the last call.
func (b *UpstreamParametersApplyConfiguration) WithUDPResponses(value int) *UpstreamParametersApplyConfiguration {
	b.UDPResponses = &value
	return b
}

// WithConnectTimeout sets the ConnectTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectTimeout field is set to the value of the last call.
func (b *UpstreamParametersApplyConfiguration) WithConnectTimeout(value string) *UpstreamParametersApplyConfiguration {
	b.ConnectTimeout = &value
	return b
}

// WithNextUpstream sets the NextUpstream field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextUpstream field is set to the value of the last call.
func (b *UpstreamParametersApplyConfiguration) WithNextUpstream(value bool) *UpstreamParametersApplyConfiguration {
	b.NextUpstream = &value
	return b
}

// WithNextUpstreamTimeout sets the NextUpstreamTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextUpstreamTimeout field is set to the value of the last call.
func (b *UpstreamParametersApplyConfiguration) WithNextUpstreamTimeout(value string) *UpstreamParametersApplyConfiguration {
	b.NextUpstreamTimeout = &value
	return b
}

// WithNextUpstreamTries sets the NextUpstreamTries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextUpstreamTries field is set to the value of the last call.
func (b *UpstreamParametersApplyConfiguration) WithNextUpstreamTries(value int) *UpstreamParametersApplyConfiguration {
	b.NextUpstreamTries = &value
	return b
}
