// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// UpstreamQueueApplyConfiguration represents a declarative configuration of the UpstreamQueue type for use
// with apply.
//
// UpstreamQueue defines Queue Configuration for an Upstream.
type UpstreamQueueApplyConfiguration struct {
	// The size of the queue.
	Size *int `json:"size,omitempty"`
	// The timeout of the queue. A request cannot be queued for a period longer than the timeout. The default is 60s.
	Timeout *string `json:"timeout,omitempty"`
}

// UpstreamQueueApplyConfiguration constructs a declarative configuration of the UpstreamQueue type for use with
// apply.
func UpstreamQueue() *UpstreamQueueApplyConfiguration {
	return &UpstreamQueueApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *UpstreamQueueApplyConfiguration) WithSize(value int) *UpstreamQueueApplyConfiguration {
	b.Size = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *UpstreamQueueApplyConfiguration) WithTimeout(value string) *UpstreamQueueApplyConfiguration {
	b.Timeout = &value
	return b
}
