// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VariableConditionApplyConfiguration represents a declarative configuration of the VariableCondition type for use
// with apply.
//
// VariableCondition defines a condition to rate limit by a variable.
type VariableConditionApplyConfiguration struct {
	// the name of the variable to match against.
	Name *string `json:"name,omitempty"`
	// the value of the variable to match against.
	Match *string `json:"match,omitempty"`
}

// VariableConditionApplyConfiguration constructs a declarative configuration of the VariableCondition type for use with
// apply.
func VariableCondition() *VariableConditionApplyConfiguration {
	return &VariableConditionApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VariableConditionApplyConfiguration) WithName(value string) *VariableConditionApplyConfiguration {
	b.Name = &value
	return b
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *VariableConditionApplyConfiguration) WithMatch(value string) *VariableConditionApplyConfiguration {
	b.Match = &value
	return b
}
