// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VirtualServerRouteSpecApplyConfiguration represents a declarative configuration of the VirtualServerRouteSpec type for use
// with apply.
//
// VirtualServerRouteSpec is the spec of the VirtualServerRoute resource.
type VirtualServerRouteSpecApplyConfiguration struct {
	// Specifies which Ingress Controller must handle the VirtualServerRoute resource. Must be the same as the ingressClassName of the VirtualServer that references this resource.
	IngressClass *string `json:"ingressClassName,omitempty"`
	// The host (domain name) of the server. Must be a valid subdomain as defined in RFC 1123, such as my-app or hello.example.com. When using a wildcard domain like *.example.com the domain must be contained in double quotes. Must be the same as the host of the VirtualServer that references this resource.
	Host *string `json:"host,omitempty"`
	// A list of upstreams.
	Upstreams []UpstreamApplyConfiguration `json:"upstreams,omitempty"`
	// A list of subroutes.
	Subroutes []RouteApplyConfiguration `json:"subroutes,omitempty"`
}

// VirtualServerRouteSpecApplyConfiguration constructs a declarative configuration of the VirtualServerRouteSpec type for use with
// apply.
func VirtualServerRouteSpec() *VirtualServerRouteSpecApplyConfiguration {
	return &VirtualServerRouteSpecApplyConfiguration{}
}

// WithIngressClass sets the IngressClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressClass field is set to the value of the last call.
func (b *VirtualServerRouteSpecApplyConfiguration) WithIngressClass(value string) *VirtualServerRouteSpecApplyConfiguration {
	b.IngressClass = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *VirtualServerRouteSpecApplyConfiguration) WithHost(value string) *VirtualServerRouteSpecApplyConfiguration {
	b.Host = &value
	return b
}

// WithUpstreams adds the given value to the Upstreams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Upstreams field.
func (b *VirtualServerRouteSpecApplyConfiguration) WithUpstreams(values ...*UpstreamApplyConfiguration) *VirtualServerRouteSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUpstreams")
		}
		b.Upstreams = append(b.Upstreams, *values[i])
	}
	return b
}

// WithSubroutes adds the given value to the Subroutes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subroutes field.
func (b *VirtualServerRouteSpecApplyConfiguration) WithSubroutes(values ...*RouteApplyConfiguration) *VirtualServerRouteSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSubroutes")
		}
		b.Subroutes = append(b.Subroutes, *values[i])
	}
	return b
}
