// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VirtualServerRouteStatusApplyConfiguration represents a declarative configuration of the VirtualServerRouteStatus type for use
// with apply.
//
// VirtualServerRouteStatus defines the status for the VirtualServerRoute resource.
type VirtualServerRouteStatusApplyConfiguration struct {
	// Represents the current state of the resource. There are three possible values: Valid, Invalid and Warning. Valid indicates that the resource has been validated and accepted by the Ingress Controller. Invalid means the resource failed validation or NGINX
	State *string `json:"state,omitempty"`
	// The reason of the current state of the resource.
	Reason *string `json:"reason,omitempty"`
	// The message of the current state of the resource. It can contain more detailed information about the reason.
	Message *string `json:"message,omitempty"`
	// Defines how other resources reference this resource.
	ReferencedBy *string `json:"referencedBy,omitempty"`
	// Defines the IPs, hostnames and ports used to connect to this resource.
	ExternalEndpoints []ExternalEndpointApplyConfiguration `json:"externalEndpoints,omitempty"`
}

// VirtualServerRouteStatusApplyConfiguration constructs a declarative configuration of the VirtualServerRouteStatus type for use with
// apply.
func VirtualServerRouteStatus() *VirtualServerRouteStatusApplyConfiguration {
	return &VirtualServerRouteStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *VirtualServerRouteStatusApplyConfiguration) WithState(value string) *VirtualServerRouteStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *VirtualServerRouteStatusApplyConfiguration) WithReason(value string) *VirtualServerRouteStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *VirtualServerRouteStatusApplyConfiguration) WithMessage(value string) *VirtualServerRouteStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithReferencedBy sets the ReferencedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReferencedBy field is set to the value of the last call.
func (b *VirtualServerRouteStatusApplyConfiguration) WithReferencedBy(value string) *VirtualServerRouteStatusApplyConfiguration {
	b.ReferencedBy = &value
	return b
}

// WithExternalEndpoints adds the given value to the ExternalEndpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalEndpoints field.
func (b *VirtualServerRouteStatusApplyConfiguration) WithExternalEndpoints(values ...*ExternalEndpointApplyConfiguration) *VirtualServerRouteStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExternalEndpoints")
		}
		b.ExternalEndpoints = append(b.ExternalEndpoints, *values[i])
	}
	return b
}
