// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VirtualServerListenerApplyConfiguration represents a declarative configuration of the VirtualServerListener type for use
// with apply.
//
// VirtualServerListener references a custom http and/or https listener defined in GlobalConfiguration.
type VirtualServerListenerApplyConfiguration struct {
	// The name of an HTTP listener defined in a GlobalConfiguration resource.
	HTTP *string `json:"http,omitempty"`
	// The name of an HTTPS listener defined in a GlobalConfiguration resource.
	HTTPS *string `json:"https,omitempty"`
}

// VirtualServerListenerApplyConfiguration constructs a declarative configuration of the VirtualServerListener type for use with
// apply.
func VirtualServerListener() *VirtualServerListenerApplyConfiguration {
	return &VirtualServerListenerApplyConfiguration{}
}

// WithHTTP sets the HTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTP field is set to the value of the last call.
func (b *VirtualServerListenerApplyConfiguration) WithHTTP(value string) *VirtualServerListenerApplyConfiguration {
	b.HTTP = &value
	return b
}

// WithHTTPS sets the HTTPS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPS field is set to the value of the last call.
func (b *VirtualServerListenerApplyConfiguration) WithHTTPS(value string) *VirtualServerListenerApplyConfiguration {
	b.HTTPS = &value
	return b
}
