// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	configurationv1 "github.com/nginx/kubernetes-ingress/pkg/apis/configuration/v1"
)

// WAFApplyConfiguration represents a declarative configuration of the WAF type for use
// with apply.
//
// The WAF policy configures NGINX Plus to secure client requests using App Protect WAF policies.
type WAFApplyConfiguration struct {
	// Enables NGINX App Protect WAF.
	Enable *bool `json:"enable,omitempty"`
	// The App Protect WAF policy of the WAF. Accepts an optional namespace. Mutually exclusive with apBundle.
	ApPolicy *string `json:"apPolicy,omitempty"`
	// The App Protect WAF policy bundle. Mutually exclusive with apPolicy.
	ApBundle     *string                        `json:"apBundle,omitempty"`
	SecurityLog  *SecurityLogApplyConfiguration `json:"securityLog,omitempty"`
	SecurityLogs []*configurationv1.SecurityLog `json:"securityLogs,omitempty"`
}

// WAFApplyConfiguration constructs a declarative configuration of the WAF type for use with
// apply.
func WAF() *WAFApplyConfiguration {
	return &WAFApplyConfiguration{}
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *WAFApplyConfiguration) WithEnable(value bool) *WAFApplyConfiguration {
	b.Enable = &value
	return b
}

// WithApPolicy sets the ApPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApPolicy field is set to the value of the last call.
func (b *WAFApplyConfiguration) WithApPolicy(value string) *WAFApplyConfiguration {
	b.ApPolicy = &value
	return b
}

// WithApBundle sets the ApBundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApBundle field is set to the value of the last call.
func (b *WAFApplyConfiguration) WithApBundle(value string) *WAFApplyConfiguration {
	b.ApBundle = &value
	return b
}

// WithSecurityLog sets the SecurityLog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityLog field is set to the value of the last call.
func (b *WAFApplyConfiguration) WithSecurityLog(value *SecurityLogApplyConfiguration) *WAFApplyConfiguration {
	b.SecurityLog = value
	return b
}

// WithSecurityLogs adds the given value to the SecurityLogs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecurityLogs field.
func (b *WAFApplyConfiguration) WithSecurityLogs(values ...**configurationv1.SecurityLog) *WAFApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSecurityLogs")
		}
		b.SecurityLogs = append(b.SecurityLogs, *values[i])
	}
	return b
}
