// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	externaldnsv1 "github.com/nginx/kubernetes-ingress/pkg/apis/externaldns/v1"
)

// DNSEndpointSpecApplyConfiguration represents a declarative configuration of the DNSEndpointSpec type for use
// with apply.
//
// DNSEndpointSpec holds information about endpoints.
type DNSEndpointSpecApplyConfiguration struct {
	Endpoints []*externaldnsv1.Endpoint `json:"endpoints,omitempty"`
}

// DNSEndpointSpecApplyConfiguration constructs a declarative configuration of the DNSEndpointSpec type for use with
// apply.
func DNSEndpointSpec() *DNSEndpointSpecApplyConfiguration {
	return &DNSEndpointSpecApplyConfiguration{}
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *DNSEndpointSpecApplyConfiguration) WithEndpoints(values ...**externaldnsv1.Endpoint) *DNSEndpointSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}
