apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: ip-intelligence-policy
spec:
  policy:
    name: ip-intelligence-policy
    enforcementMode: blocking
    blocking-settings:
      violations:
        - alarm: true
        - block: true
        - name: VIOL_MALICIOUS_IP
    ip-intelligence:
      ipIntelligenceCategories:
        - category: Anonymous Proxy
          block: true
          alarm: true
        - category: BotNets
          block: true
          alarm: true
        - category: Cloud-based Services
          block: true
          alarm: true
        - category: Denial of Service
          block: true
          alarm: true
        - category: Infected Sources
          block: true
          alarm: true
        - category: Mobile Threats
          block: true
          alarm: true
        - category: Phishing Proxies
          block: true
          alarm: true
        - category: Scanners
          block: true
          alarm: true
