// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	configurationv1 "github.com/nginx/kubernetes-ingress/pkg/apis/configuration/v1"
	v1beta1 "github.com/nginx/kubernetes-ingress/pkg/apis/dos/v1beta1"
	v1 "github.com/nginx/kubernetes-ingress/pkg/apis/externaldns/v1"
	applyconfigurationconfigurationv1 "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/configuration/v1"
	dosv1beta1 "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/dos/v1beta1"
	externaldnsv1 "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/externaldns/v1"
	internal "github.com/nginx/kubernetes-ingress/pkg/client/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=appprotectdos.f5.com, Version=v1beta1
	case v1beta1.SchemeGroupVersion.WithKind("AllowListEntry"):
		return &dosv1beta1.AllowListEntryApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("ApDosMonitor"):
		return &dosv1beta1.ApDosMonitorApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("DosProtectedResource"):
		return &dosv1beta1.DosProtectedResourceApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("DosProtectedResourceSpec"):
		return &dosv1beta1.DosProtectedResourceSpecApplyConfiguration{}
	case v1beta1.SchemeGroupVersion.WithKind("DosSecurityLog"):
		return &dosv1beta1.DosSecurityLogApplyConfiguration{}

		// Group=externaldns.nginx.org, Version=v1
	case v1.SchemeGroupVersion.WithKind("DNSEndpoint"):
		return &externaldnsv1.DNSEndpointApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DNSEndpointSpec"):
		return &externaldnsv1.DNSEndpointSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DNSEndpointStatus"):
		return &externaldnsv1.DNSEndpointStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Endpoint"):
		return &externaldnsv1.EndpointApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ProviderSpecificProperty"):
		return &externaldnsv1.ProviderSpecificPropertyApplyConfiguration{}

		// Group=k8s.nginx.org, Version=v1
	case configurationv1.SchemeGroupVersion.WithKind("AccessControl"):
		return &applyconfigurationconfigurationv1.AccessControlApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Action"):
		return &applyconfigurationconfigurationv1.ActionApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ActionProxy"):
		return &applyconfigurationconfigurationv1.ActionProxyApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ActionRedirect"):
		return &applyconfigurationconfigurationv1.ActionRedirectApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ActionReturn"):
		return &applyconfigurationconfigurationv1.ActionReturnApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("AddHeader"):
		return &applyconfigurationconfigurationv1.AddHeaderApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("APIKey"):
		return &applyconfigurationconfigurationv1.APIKeyApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("BasicAuth"):
		return &applyconfigurationconfigurationv1.BasicAuthApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Cache"):
		return &applyconfigurationconfigurationv1.CacheApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("CacheConditions"):
		return &applyconfigurationconfigurationv1.CacheConditionsApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("CacheLock"):
		return &applyconfigurationconfigurationv1.CacheLockApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("CacheManager"):
		return &applyconfigurationconfigurationv1.CacheManagerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("CertManager"):
		return &applyconfigurationconfigurationv1.CertManagerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Condition"):
		return &applyconfigurationconfigurationv1.ConditionApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("EgressMTLS"):
		return &applyconfigurationconfigurationv1.EgressMTLSApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ErrorPage"):
		return &applyconfigurationconfigurationv1.ErrorPageApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ErrorPageRedirect"):
		return &applyconfigurationconfigurationv1.ErrorPageRedirectApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ErrorPageReturn"):
		return &applyconfigurationconfigurationv1.ErrorPageReturnApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ExternalDNS"):
		return &applyconfigurationconfigurationv1.ExternalDNSApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ExternalEndpoint"):
		return &applyconfigurationconfigurationv1.ExternalEndpointApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("GlobalConfiguration"):
		return &applyconfigurationconfigurationv1.GlobalConfigurationApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("GlobalConfigurationSpec"):
		return &applyconfigurationconfigurationv1.GlobalConfigurationSpecApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Header"):
		return &applyconfigurationconfigurationv1.HeaderApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("HealthCheck"):
		return &applyconfigurationconfigurationv1.HealthCheckApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("IngressMTLS"):
		return &applyconfigurationconfigurationv1.IngressMTLSApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("JWTAuth"):
		return &applyconfigurationconfigurationv1.JWTAuthApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("JWTCondition"):
		return &applyconfigurationconfigurationv1.JWTConditionApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Listener"):
		return &applyconfigurationconfigurationv1.ListenerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Match"):
		return &applyconfigurationconfigurationv1.MatchApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("OIDC"):
		return &applyconfigurationconfigurationv1.OIDCApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Policy"):
		return &applyconfigurationconfigurationv1.PolicyApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("PolicyReference"):
		return &applyconfigurationconfigurationv1.PolicyReferenceApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("PolicySpec"):
		return &applyconfigurationconfigurationv1.PolicySpecApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("PolicyStatus"):
		return &applyconfigurationconfigurationv1.PolicyStatusApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ProviderSpecificProperty"):
		return &applyconfigurationconfigurationv1.ProviderSpecificPropertyApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ProxyRequestHeaders"):
		return &applyconfigurationconfigurationv1.ProxyRequestHeadersApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("ProxyResponseHeaders"):
		return &applyconfigurationconfigurationv1.ProxyResponseHeadersApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("RateLimit"):
		return &applyconfigurationconfigurationv1.RateLimitApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("RateLimitCondition"):
		return &applyconfigurationconfigurationv1.RateLimitConditionApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Route"):
		return &applyconfigurationconfigurationv1.RouteApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("SecurityLog"):
		return &applyconfigurationconfigurationv1.SecurityLogApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("SessionCookie"):
		return &applyconfigurationconfigurationv1.SessionCookieApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("SessionParameters"):
		return &applyconfigurationconfigurationv1.SessionParametersApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Split"):
		return &applyconfigurationconfigurationv1.SplitApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("SuppliedIn"):
		return &applyconfigurationconfigurationv1.SuppliedInApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TLS"):
		return &applyconfigurationconfigurationv1.TLSApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TLSRedirect"):
		return &applyconfigurationconfigurationv1.TLSRedirectApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServer"):
		return &applyconfigurationconfigurationv1.TransportServerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerAction"):
		return &applyconfigurationconfigurationv1.TransportServerActionApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerHealthCheck"):
		return &applyconfigurationconfigurationv1.TransportServerHealthCheckApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerListener"):
		return &applyconfigurationconfigurationv1.TransportServerListenerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerMatch"):
		return &applyconfigurationconfigurationv1.TransportServerMatchApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerSpec"):
		return &applyconfigurationconfigurationv1.TransportServerSpecApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerStatus"):
		return &applyconfigurationconfigurationv1.TransportServerStatusApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerTLS"):
		return &applyconfigurationconfigurationv1.TransportServerTLSApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("TransportServerUpstream"):
		return &applyconfigurationconfigurationv1.TransportServerUpstreamApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("Upstream"):
		return &applyconfigurationconfigurationv1.UpstreamApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("UpstreamBuffers"):
		return &applyconfigurationconfigurationv1.UpstreamBuffersApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("UpstreamParameters"):
		return &applyconfigurationconfigurationv1.UpstreamParametersApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("UpstreamQueue"):
		return &applyconfigurationconfigurationv1.UpstreamQueueApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("UpstreamTLS"):
		return &applyconfigurationconfigurationv1.UpstreamTLSApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VariableCondition"):
		return &applyconfigurationconfigurationv1.VariableConditionApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServer"):
		return &applyconfigurationconfigurationv1.VirtualServerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServerListener"):
		return &applyconfigurationconfigurationv1.VirtualServerListenerApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServerRoute"):
		return &applyconfigurationconfigurationv1.VirtualServerRouteApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServerRouteSpec"):
		return &applyconfigurationconfigurationv1.VirtualServerRouteSpecApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServerRouteStatus"):
		return &applyconfigurationconfigurationv1.VirtualServerRouteStatusApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServerSpec"):
		return &applyconfigurationconfigurationv1.VirtualServerSpecApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("VirtualServerStatus"):
		return &applyconfigurationconfigurationv1.VirtualServerStatusApplyConfiguration{}
	case configurationv1.SchemeGroupVersion.WithKind("WAF"):
		return &applyconfigurationconfigurationv1.WAFApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
