// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	configurationv1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualServerLister helps list VirtualServers.
// All objects returned here must be treated as read-only.
type VirtualServerLister interface {
	// List lists all VirtualServers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*configurationv1.VirtualServer, err error)
	// VirtualServers returns an object that can list and get VirtualServers.
	VirtualServers(namespace string) VirtualServerNamespaceLister
	VirtualServerListerExpansion
}

// virtualServerLister implements the VirtualServerLister interface.
type virtualServerLister struct {
	listers.ResourceIndexer[*configurationv1.VirtualServer]
}

// NewVirtualServerLister returns a new VirtualServerLister.
func NewVirtualServerLister(indexer cache.Indexer) VirtualServerLister {
	return &virtualServerLister{listers.New[*configurationv1.VirtualServer](indexer, configurationv1.Resource("virtualserver"))}
}

// VirtualServers returns an object that can list and get VirtualServers.
func (s *virtualServerLister) VirtualServers(namespace string) VirtualServerNamespaceLister {
	return virtualServerNamespaceLister{listers.NewNamespaced[*configurationv1.VirtualServer](s.ResourceIndexer, namespace)}
}

// VirtualServerNamespaceLister helps list and get VirtualServers.
// All objects returned here must be treated as read-only.
type VirtualServerNamespaceLister interface {
	// List lists all VirtualServers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*configurationv1.VirtualServer, err error)
	// Get retrieves the VirtualServer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*configurationv1.VirtualServer, error)
	VirtualServerNamespaceListerExpansion
}

// virtualServerNamespaceLister implements the VirtualServerNamespaceLister
// interface.
type virtualServerNamespaceLister struct {
	listers.ResourceIndexer[*configurationv1.VirtualServer]
}
