apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
spec:
  oidc:
    clientID: nginx-plus
    pkceEnable: true
    authEndpoint: https://keycloak.example.com/realms/master/protocol/openid-connect/auth
    tokenEndpoint: https://keycloak.default.svc.cluster.local:8443/realms/master/protocol/openid-connect/token
    jwksURI: https://keycloak.default.svc.cluster.local:8443/realms/master/protocol/openid-connect/certs
    endSessionEndpoint: https://keycloak.example.com/realms/master/protocol/openid-connect/logout
    scope: openid+profile+email
    accessTokenEnable: true
    sslVerify: true
    trustedCertSecret: keycloak-ca
