// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	configurationv1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1"
	scheme "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PoliciesGetter has a method to return a PolicyInterface.
// A group's client should implement this interface.
type PoliciesGetter interface {
	Policies(namespace string) PolicyInterface
}

// PolicyInterface has methods to work with Policy resources.
type PolicyInterface interface {
	Create(ctx context.Context, policy *configurationv1.Policy, opts metav1.CreateOptions) (*configurationv1.Policy, error)
	Update(ctx context.Context, policy *configurationv1.Policy, opts metav1.UpdateOptions) (*configurationv1.Policy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, policy *configurationv1.Policy, opts metav1.UpdateOptions) (*configurationv1.Policy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*configurationv1.Policy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*configurationv1.PolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *configurationv1.Policy, err error)
	PolicyExpansion
}

// policies implements PolicyInterface
type policies struct {
	*gentype.ClientWithList[*configurationv1.Policy, *configurationv1.PolicyList]
}

// newPolicies returns a Policies
func newPolicies(c *K8sV1Client, namespace string) *policies {
	return &policies{
		gentype.NewClientWithList[*configurationv1.Policy, *configurationv1.PolicyList](
			"policies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *configurationv1.Policy { return &configurationv1.Policy{} },
			func() *configurationv1.PolicyList { return &configurationv1.PolicyList{} },
		),
	}
}
