// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	configurationv1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1"
	scheme "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VirtualServerRoutesGetter has a method to return a VirtualServerRouteInterface.
// A group's client should implement this interface.
type VirtualServerRoutesGetter interface {
	VirtualServerRoutes(namespace string) VirtualServerRouteInterface
}

// VirtualServerRouteInterface has methods to work with VirtualServerRoute resources.
type VirtualServerRouteInterface interface {
	Create(ctx context.Context, virtualServerRoute *configurationv1.VirtualServerRoute, opts metav1.CreateOptions) (*configurationv1.VirtualServerRoute, error)
	Update(ctx context.Context, virtualServerRoute *configurationv1.VirtualServerRoute, opts metav1.UpdateOptions) (*configurationv1.VirtualServerRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualServerRoute *configurationv1.VirtualServerRoute, opts metav1.UpdateOptions) (*configurationv1.VirtualServerRoute, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*configurationv1.VirtualServerRoute, error)
	List(ctx context.Context, opts metav1.ListOptions) (*configurationv1.VirtualServerRouteList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *configurationv1.VirtualServerRoute, err error)
	VirtualServerRouteExpansion
}

// virtualServerRoutes implements VirtualServerRouteInterface
type virtualServerRoutes struct {
	*gentype.ClientWithList[*configurationv1.VirtualServerRoute, *configurationv1.VirtualServerRouteList]
}

// newVirtualServerRoutes returns a VirtualServerRoutes
func newVirtualServerRoutes(c *K8sV1Client, namespace string) *virtualServerRoutes {
	return &virtualServerRoutes{
		gentype.NewClientWithList[*configurationv1.VirtualServerRoute, *configurationv1.VirtualServerRouteList](
			"virtualserverroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *configurationv1.VirtualServerRoute { return &configurationv1.VirtualServerRoute{} },
			func() *configurationv1.VirtualServerRouteList { return &configurationv1.VirtualServerRouteList{} },
		),
	}
}
