name: Build Test Image

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force rebuild of test image"
        required: false
        default: "false"
  schedule:
    - cron: "0 3 * * *" # run every day at 03:00 UTC

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-build-test
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build test image
    if: github.repository == 'nginx/kubernetes-ingress'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Setup secrets
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: "${{ secrets.AZURE_VAULT_CLIENT_ID }}"
          tenant-id: "${{ secrets.AZURE_VAULT_TENANT_ID }}"
          vault-name: ${{ secrets.NIC_KEYVAULT_NAME }}
          secret-names: "gcr-workload-identity, kic-pipeline-gcr-sa"
          env-names: "GCR_WORKLOAD_ID, GCR_SERVICE_ACCOUNT"

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.GCR_WORKLOAD_ID }}
          service_account: ${{ env.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Test-Runner Container
        uses: ./.github/actions/build-push-retry
        with:
          file: tests/Dockerfile
          context: "."
          cache-from: type=gha,scope=test-runner
          tags: |
            gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') }}
            gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:latest
          pull: true
          push: true
