name: Build UBI Dependencies

on:
  push:
    branches:
      - main
    paths:
      - build/dependencies/Dockerfile.ubi10
      - .github/workflows/build-ubi-dependency.yml
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/nginx/dependencies/nginx-ubi

concurrency:
  group: ${{ github.ref_name }}-ubi-build
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-binaries:
    name: Build Binary Container Image
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        tag: ["ubi10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Azure Login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        run: |
          RHEL_CREDS=$(az keyvault secret show --name rhel-creds --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$RHEL_CREDS"
          echo "$RHEL_CREDS" > rhel_license
          PLUS_CREDS=$(az keyvault secret show --name plus-creds --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$PLUS_CREDS"
          IFS=@ CERT=$(echo "$PLUS_CREDS" | jq -r '.crt')
          while read -r line; do
            echo "::add-mask::${line}"
          done <<< "${CERT}"
          echo "$CERT" > nginx-repo.crt
          IFS=@ KEY=$(echo "$PLUS_CREDS" | jq -r '.key')
          while read -r line; do
            echo "::add-mask::${line}"
          done <<< "${KEY}"
          echo "$KEY" > nginx-repo.key

      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: arm64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize ref name
        id: ref
        run: echo "name=$(echo '${{ github.ref_name }}' | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            name=${{ env.IMAGE_NAME }},enable=true
          tags: |
            type=raw,value=${{ matrix.tag }},enable=${{ github.ref_name == 'main' }}
            type=raw,value=${{ matrix.tag }}-${{ steps.ref.outputs.name }},enable=${{ github.ref_name != 'main' }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: ./build/dependencies/Dockerfile.${{ matrix.tag }}
          context: "."
          pull: true
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha,scope=nginx-${{ matrix.tag }}
          target: final
          sbom: false
          provenance: mode=max
          secret-files: |
            rhel_license=rhel_license
            nginx-repo.crt=nginx-repo.crt
            nginx-repo.key=nginx-repo.key

      - name: Clean up secrets
        if: always()
        run: rm -f rhel_license nginx-repo.*
