name: Build UBI Dependencies

on:
  push:
    branches:
      - main
    paths:
      - build/dependencies/Dockerfile.ubi10
      - .github/workflows/build-ubi-dependency.yml
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/nginx/dependencies/nginx-ubi

concurrency:
  group: ${{ github.ref_name }}-ubi-build
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-binaries:
    name: Build Binary Container Image
    if: github.repository == 'nginx/kubernetes-ingress'
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        tag: ["ubi10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup NIC secrets
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: "${{ secrets.AZURE_VAULT_CLIENT_ID }}"
          tenant-id: "${{ secrets.AZURE_VAULT_TENANT_ID }}"
          vault-name: ${{ secrets.NIC_KEYVAULT_NAME }}
          secret-names: "rhel-creds"
          env-names: "RHEL_CREDS"

      - name: Setup Common secrets
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: "${{ secrets.AZURE_COMMON_VAULT_CLIENT_ID }}"
          tenant-id: "${{ secrets.AZURE_COMMON_VAULT_TENANT_ID }}"
          vault-name: ${{ secrets.COMMON_KEYVAULT_NAME }}
          secret-names: "nginx-pkg-certificate, nginx-pkg-key"
          env-names: "PLUS_CERT, PLUS_KEY"

      - name: Write secrets
        run: |
          echo "$RHEL_CREDS" > rhel_license
          echo "$PLUS_CERT" > nginx-repo.crt
          echo "$PLUS_KEY" > nginx-repo.key

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          platforms: arm64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize ref name
        id: ref
        run: echo "name=$(echo '${{ github.ref_name }}' | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            name=${{ env.IMAGE_NAME }},enable=true
          tags: |
            type=raw,value=${{ matrix.tag }},enable=${{ github.ref_name == 'main' }}
            type=raw,value=${{ matrix.tag }}-${{ steps.ref.outputs.name }},enable=${{ github.ref_name != 'main' }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push
        uses: ./.github/actions/build-push-retry
        with:
          file: ./build/dependencies/Dockerfile.${{ matrix.tag }}
          context: "."
          pull: true
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha,scope=nginx-${{ matrix.tag }}
          target: final
          sbom: false
          provenance: mode=max
          secret-files: |
            rhel_license=rhel_license
            nginx-repo.crt=nginx-repo.crt
            nginx-repo.key=nginx-repo.key

      - name: Clean up secrets
        if: always()
        run: rm -f rhel_license nginx-repo.*
