name: Certify UBI image
run-name: Certify UBI image ${{ inputs.image }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to certify"
        required: true
        type: string
      submit:
        description: "Submit results to Redhat"
        required: false
        type: boolean
        default: false
      preflight_version:
        description: "Preflight version to use"
        required: false
        type: string
        default: "1.14.1"
      platforms:
        description: A comma separated list of architectures in the image manifest to certify
        required: false
        default: "amd64,arm64"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  certify-ubi-images:
    name: Certify OpenShift UBI images
    if: github.repository == 'nginx/kubernetes-ingress'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup secrets
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: "${{ secrets.AZURE_VAULT_CLIENT_ID }}"
          tenant-id: "${{ secrets.AZURE_VAULT_TENANT_ID }}"
          vault-name: ${{ secrets.NIC_KEYVAULT_NAME }}
          secret-names: "nic-pyxis-token, nic-pyxis-certification-pid"
          env-names: "PYXIS_TOKEN, PYXIS_CERTIFICATION_PROJECT_ID"

      - name: Certify UBI OSS images in quay
        uses: ./.github/actions/certify-openshift-image
        with:
          image: ${{ inputs.image }}
          project_id: ${{ env.PYXIS_CERTIFICATION_PROJECT_ID }}
          pyxis_token: ${{ env.PYXIS_TOKEN }}
          preflight_version: ${{ inputs.preflight_version }}
          submit: ${{ inputs.submit || true }}
          platforms: ${{ inputs.platforms }}
