name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

concurrency:
  group: ${{ github.ref_name }}-dockerhub
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dockerHubDescription:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    if: github.repository == 'nginx/kubernetes-ingress' && (github.event.repository.fork == false)
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Common secrets
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: "${{ secrets.AZURE_COMMON_VAULT_CLIENT_ID }}"
          tenant-id: "${{ secrets.AZURE_COMMON_VAULT_TENANT_ID }}"
          vault-name: ${{ secrets.COMMON_KEYVAULT_NAME }}
          secret-names: "docker-username, docker-password"
          env-names: "DOCKER_USERNAME, DOCKER_PASSWORD"

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: nginx/nginx-ingress
          short-description: ${{ github.event.repository.description }}
