name: "Bump the IC & Helm chart version"

on:
  workflow_dispatch:
    inputs:
      source_branch:
        required: true
        type: string
        default: "main"
      ic_version:
        required: true
        type: string
        default: "0.0.0"
      helm_chart_version:
        required: true
        type: string
        default: "0.0.0"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  version-bump:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.source_branch }}

      - name: Replace Versions
        run: |
          yq -i e '.version = env(CHART_VERSION) | .appVersion = env(IC_VERSION)' charts/nginx-ingress/Chart.yaml
          cat charts/nginx-ingress/Chart.yaml
          cat > .github/data/version.txt << EOF
          IC_VERSION=${IC_VERSION}
          HELM_CHART_VERSION=${CHART_VERSION}
          EOF
          cat .github/data/version.txt
        env:
          IC_VERSION: ${{ inputs.ic_version }}
          CHART_VERSION: ${{ inputs.helm_chart_version }}

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod

      - name: Generate test secrets
        run: |
          make secrets

      - name: Update Snapshots
        run: |
          make test-update-snaps

      - name: Azure login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_COMMON_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_COMMON_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_COMMON_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          NGINX_PAT=$(az keyvault secret show --name nginx-bot-pat --vault-name ${{ secrets.COMMON_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$NGINX_PAT"
          echo "NGINX_PAT=$NGINX_PAT" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.secrets.outputs.NGINX_PAT }}
          commit-message: Version Bump for ${{ github.event.inputs.ic_version }}
          title: Version Bump for ${{ github.event.inputs.ic_version }}
          branch: chore/version-bump-${{ github.event.inputs.ic_version }}
          labels: chore
          body: |
            This automated PR updates the NIC & Helm chart versions for the upcoming ${{ github.event.inputs.ic_version }} release.
